Add new accessibility sanitizer
Automattic/amp-wp pull request #4535
Opened 2020-04-06 13:26 UTC by schlessera

## Summary

This PR includes the following changes:

- Adds a new `AMP_Accessibility_Sanitizer` class that adds `role` and `tabindex` attributes to elements with the `on` AMP event.
- Ports over the `MarkupComparison` trait from the `amp/common` test suite and replaces copy-pasted `assertEqualMarkup()` methods throughout tests with the new trait.
- Adds a `Role` interface to define and document ARIA roles and use the provided constants instead of hard-coded strings in existing sanitizers/transformers that define ARIA roles.

Fixes #4528

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

2020-04-08 04:40 UTC, pierlon requested changes
You forgot the most important part, adding it to the list of sanitizers to be run:

```diff
--- includes/amp-helper-functions.php	(revision f0c97bbfaddbc59f44e0c9508aa63d1be367a912)
+++ includes/amp-helper-functions.php	(date 1586320714141)
@@ -1220,6 +1220,7 @@
 		'AMP_Style_Sanitizer'             => [],
 		'AMP_Meta_Sanitizer'              => [],
 		'AMP_Layout_Sanitizer'            => [],
+		'AMP_Accessibility_Sanitizer'     => [],
 		'AMP_Tag_And_Attribute_Sanitizer' => [], // Note: This whitelist sanitizer must come at the end to clean up any remaining issues the other sanitizers didn't catch.
 	];
 ```

2020-04-10 05:21 UTC, westonruter approved these changes

2020-04-10 14:55 UTC, pierlon approved these changes

2020-04-10 16:57 UTC, merged

2020-04-14 17:52 UTC, amedina commented on tests/php/test-class-amp-accessibility-sanitizer.php
> +				'<div href="#" on="tap:some_id.toggleClass(some_class)" role="button" tabindex="0"></div>',
@schlessera The validator complains against `href="#"`; it is not valid markup.

2020-04-14 17:56 UTC, amedina commented on tests/php/test-class-amp-accessibility-sanitizer.php
> +				'<div href="#" on="tap:some_id.toggleClass(some_class)" role="button" tabindex="0"></div>',
Does the test catch that?

2020-04-14 18:01 UTC, amedina commented
Would like to validate the acceptance criteria here. These HTML blocks:

![Screen Shot 2020-04-14 at 10 55 05 AM](https://user-images.githubusercontent.com/506089/79257904-2e1e5280-7e3f-11ea-8632-54f370187dd6.png)

Should yield the corresponding `role` and/or `tabindex` attributes

![Screen Shot 2020-04-14 at 10 57 47 AM](https://user-images.githubusercontent.com/506089/79257911-31b1d980-7e3f-11ea-8058-a460bb5c348f.png)

2020-04-14 18:29 UTC, kienstra commented
This looks good in my local.

On copying the Custom HTML markup above verbatim into Custom HTML blocks:

```html
<div on="tap:myfunction()">
None in
</div>

<div on="tap:myfunction()" tabindex="1">
Tabindex in
</div>

<div on="tap:myfunction()" role="button">
Role in
</div>
```

...the `tabindex` and `role` appear as expected:

![tabindex](https://user-images.githubusercontent.com/4063887/79260510-02f22e00-7e54-11ea-9570-a0a6e8121c48.png)

2020-04-14 18:46 UTC, amedina commented
Thanks @kienstra ; reason was missing `composer install` run