Make collection the default Schema.org type for archive queries
Automattic/amp-wp pull request #4680
Opened 2020-05-11 01:05 UTC by westonruter

## Summary

Addresses issue #4666

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-05-11 01:08 UTC, westonruter commented
Question: When the queried object is a user, should the `@type` not be `collection` but something more “authory”?

2020-05-11 17:31 UTC, pierlon commented
The Yoast SEO plugin identifies these pages as a [CollectionPage](https://github.com/Yoast/wordpress-seo/blob/19e029e95929c5f5c0cd4b3d9e93915febea3270/src/context/meta-tags-context.php#L386-L390).

2020-05-14 06:39 UTC, schlessera requested changes

2020-05-14 06:39 UTC, schlessera commented on includes/amp-helper-functions.php
> +		$metadata['@type'] = 'collection';
I agree with @pierlon, we should use `CollectionPage` here, as it is a `WebPage` _containing_  a `Collection`.

Also, I'd stick to the casing of the official type reference.
```suggestion
		$metadata['@type'] = 'CollectionPage';
```

2020-05-14 06:39 UTC, schlessera commented on tests/php/test-amp-helper-functions.php
> +		$this->assertEquals( 'collection', $metadata['@type'] );
```suggestion
		$this->assertEquals( 'CollectionPage', $metadata['@type'] );
```

2020-05-15 04:16 UTC, pierlon commented
Seems like Travis lost its way back to this PR to give its report. Maybe another push would help?

2020-05-20 23:13 UTC, pierlon approved these changes

2020-05-20 23:38 UTC, merged