Fix failing Optimizer spec tests with ID generation
Automattic/amp-wp pull request #4799
Opened 2020-05-29 08:20 UTC by schlessera

## Summary

Fixes the spec test failures introduced by the merge of https://github.com/ampproject/amp-toolbox/pull/763 in the `ampproject/amp-toolbox` package.

- Changes the default prefix for `Document::getElementId()` from `i-amp-id` to `i-amp`
- Changes the indexing behavior for `Document::getElementId()` to start with `0` instead of `1`
- Changes the indexing behavior for `Document::getElementId()` to always add the index instead of skipping the first instance
- Skips the following tests until https://github.com/ampproject/amp-toolbox/issues/809 is resolved:
	- `'ServerSideRendering - converts_sizes_attribute_to_css'`
	- `'ServerSideRendering - converts_heights_attribute_to_css'`
	- `'ServerSideRendering - converts_media_attribute_to_css'`

Addresses issue #4798

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-05-29 20:44 UTC, westonruter commented
There's one remaining test failure:

```
1) AmpProject\Optimizer\SpecTest::testTransformerSpecFiles with data set "ServerSideRendering - converts_media_attribute_to_css" ('ServerSideRendering - convert...to_css', 'AmpProject\Optimizer\Transfor...dering', '<html :zap:>\n  <head>\n    <scri...tml>\n', '<html :zap: i-amphtml-layout i-am.../html>')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-    21 => '@media not all and (min-width: 650px){#i-amp-0,#my-image,#i-amp-4{display:none}}@media not screen and (min-width: 650px){#i-amp-1{display:none}}@media screen and (min-width: 650px){#i-amp-2{display:none}}@media (min-width: 650px){#i-amp-3,#i-amp-5,#i-amp-6{display:none}}'
+    21 => '@media not all and (min-width: 650px){#i-amp-0{display:none}}@media not screen and (min-width: 650px){#i-amp-1{display:none}}@media not not screen and (min-width: 650px){#i-amp-2{display:none}}@media not not (min-width: 650px){#i-amp-3{display:none}}@media not not (min-width: 650px){#i-amp-5{display:none}}@media not not (min-width: 650px){#i-amp-6{display:none}}@media not all and (min-width: 650px){#my-image{display:none}}@media not all and (min-width: 650px){#i-amp-4{display:none}}'
/app/public/content/plugins/amp/lib/optimizer/tests/src/MarkupComparison.php:45
/app/public/content/plugins/amp/lib/optimizer/tests/src/MarkupComparison.php:65
/app/public/content/plugins/amp/lib/optimizer/tests/SpecTest.php:120
```

2020-05-29 20:59 UTC, westonruter requested changes
One more failing test.

2020-06-01 16:51 UTC, schlessera commented on lib/optimizer/tests/src/MarkupComparison.php
> +        $this->assertEquals( $expected_tokens, $actual_tokens );
This should actually go into `assertSimilarMarkup()`, not `assertEqualMarkup()`.

2020-06-01 17:52 UTC, westonruter commented on lib/optimizer/tests/src/MarkupComparison.php
> +        $this->assertEquals( $expected_tokens, $actual_tokens );
Ok, feel free to revert.

Should `assertSimilarMarkup()` be used in the failing tests then?

Or should the underlying order of the attributes be fixed?

2020-06-01 18:06 UTC, schlessera commented on lib/optimizer/tests/src/MarkupComparison.php
> +        $this->assertEquals( $expected_tokens, $actual_tokens );
I'm already working on fixing everything. The first should be used where we want to enforce exact markup, the second where we just want to ensure the functionality stays the same.
Here, I'll use the second, as the logic is different from both packages in when they generate the ID. So the only thing that moves around is where in the attributes list the ID is defined.

2020-06-02 06:57 UTC, westonruter approved these changes
Looks perfect. Great job.

2020-06-02 06:58 UTC, merged