Remove the `wp-has-aspect-ratio` class from block embeds
Automattic/amp-wp pull request #4813
Opened 2020-06-05 07:49 UTC by pierlon

## Summary

As of Gutenberg 8.2, when the `wp-has-aspect-ratio` class is set on an embed block, it adds a large gap to the top of the embed. This breaks the visual parity of the AMP page when compared to its non-AMP counterpart. For example:

![](https://user-images.githubusercontent.com/16200219/83850389-5f5d2580-a700-11ea-98dc-cd57c13eeda3.png)

The `wp-has-aspect-ratio` class is not needed in the AMP context because the responsive layout of the embed will be handled natively. When the class is removed, visual parity is restored:

![image](https://user-images.githubusercontent.com/16200219/83850687-cbd82480-a700-11ea-8ab2-5898b4740d72.png)

Fixes #4810

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-06-07 07:05 UTC, westonruter commented
I can see this change between 8.1 and 8.2:

![image](https://user-images.githubusercontent.com/134745/83962426-2a60e800-a852-11ea-954f-e1bdd4921d02.png)

It came from this PR: https://github.com/WordPress/gutenberg/pull/21599

2020-06-07 07:13 UTC, westonruter commented
So what was formerly:

```css
.wp-embed-responsive .wp-block-embed.wp-embed-aspect-16-9 .wp-block-embed__wrapper::before {
    padding-top: 56.25%;
}
```

Is now:

```css
.wp-embed-responsive .wp-embed-aspect-16-9 .wp-block-embed__wrapper:before {
    padding-top: 56.25%;
}
```

2020-06-07 07:16 UTC, westonruter commented
Basically we want to prevent this new CSS rule from applying:

![image](https://user-images.githubusercontent.com/134745/83962665-14542700-a854-11ea-8ac8-957ff223a2bd.png)

2020-06-07 07:17 UTC, westonruter commented
And this is the result when the `wp-has-aspect-ratio` class is removed.

2020-06-07 07:27 UTC, westonruter requested changes

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			}
I think this could be simplified to just:

```suggestion
			$classes = array_diff( $classes, [ 'wp-has-aspect-ratio' ] );
```

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +				$classes
TIL: You can pass an array to `preg_replace()`.

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +				'/wp-embed-aspect-(?P<width>\d+)-(?P<height>\d+)/',
Given the classes are separated into an array, this should be technically anchored to the start and end of the string:

```suggestion
				'/^wp-embed-aspect-(?P<width>\d+)-(?P<height>\d+)$/',
```

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			$classes = preg_replace_callback(
As opposed to using `preg_replace_callback()` would it make more sense to use `array_filter()`? So perhaps this would be marginally better:

```php
$classes = array_filter(
	$classes,
	static function ( $class ) use ( &$responsive_width, &$responsive_height ) {
		if ( preg_match( '/^wp-embed-aspect-(?P<width>\d+)-(?P<height>\d+)$/', $class, $matches ) ) {
			$responsive_width  = $matches['width'];
			$responsive_height = $matches['height'];
			return false;
		}
		return 'wp-has-aspect-ratio' !== $class;
	}
);
```

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			$classes = preg_replace_callback(
For that matter, this could also be used instead of the `array_diff()` above as well. (Now updated the above.)

2020-06-07 07:27 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			}
Actually this could be removed entirely in favor of the use of my proposed `array_filter()` below.

2020-06-08 12:42 UTC, pierlon commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			$classes = preg_replace_callback(
Addressed in https://github.com/ampproject/amp-wp/pull/4813/commits/ae7819095b947b714d2739d2565aec1e489e4a74.

2020-06-08 20:31 UTC, westonruter approved these changes

2020-06-08 20:31 UTC, westonruter commented on includes/sanitizers/class-amp-block-sanitizer.php
> +			$node->setAttribute( 'class', implode( ' ', array_filter( $classes ) ) );
Minor thing, but the `array_filter()` here can now be removed.

```suggestion
			$node->setAttribute( 'class', implode( ' ', $classes ) );
```

2020-06-08 20:38 UTC, westonruter commented
I've confirmed that an embed looks properly in WP 5.4 both when Gutenberg 8.3 is active and when it is inactive.

2020-06-09 01:20 UTC, merged