Add paragraph about serverside rendering to README
Automattic/amp-wp pull request #4841
Opened 2020-06-12 23:43 UTC by schlessera

## Summary

Adds a short paragraph with marketing buzz about the serverside rendering and the AMP optimizer.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-06-12 23:45 UTC, westonruter approved these changes

2020-06-13 20:49 UTC, amedina approved these changes
LGTM.

2020-06-13 22:11 UTC, westonruter requested changes
I don't think we can say “full integration” of the AMP Optimizer because it's not actually integrating it. We have ported it. And it's not a full port.

2020-06-13 22:11 UTC, westonruter commented on readme.md
> +- **Server-side Rendering**: full integration of the [AMP Optimizer library](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) providing automated server-side rendering of AMP
```suggestion
- **Server-side Rendering**: integrates a PHP-port of the [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) providing automated [server-side rendering](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/server-side-rendering/) of AMP pages, drastically improving the [Last Contentful Paint](https://web.dev/lcp/) (LCP) metric.
```

2020-06-13 22:11 UTC, westonruter commented on readme.txt
> +- **Server-side Rendering**: full integration of the [AMP Optimizer library](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) providing automated server-side rendering of AMP
```suggestion
- **Server-side Rendering**: integrates a PHP-port of the [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) providing automated [server-side rendering](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/server-side-rendering/) of AMP pages, drastically improving the [Last Contentful Paint](https://web.dev/lcp/) (LCP) metric.
```

2020-06-13 22:12 UTC, westonruter commented on readme.md
> +- **Server-side Rendering**: full integration of the [AMP Optimizer library](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) providing automated server-side rendering of AMP
Note I've also opened a PR to add a mention of the AMP plugin in the AMP docs for SSR: https://github.com/ampproject/amp.dev/pull/4076

2020-06-13 22:47 UTC, amedina commented
> I don't think we can say “full integration” of the AMP Optimizer because it's not actually integrating it. We have ported it. And it's not a full port.

Great point/catch. I am going to make a small tweak...

2020-06-13 22:53 UTC, westonruter commented
Diff of a diff of a diff:

![image](https://user-images.githubusercontent.com/134745/84580694-05a6cc00-ad8e-11ea-952e-bad4801d19df.png)

I love it.

2020-06-13 23:46 UTC, westonruter approved these changes

2020-06-14 01:41 UTC, westonruter approved these changes

2020-06-14 01:41 UTC, merged

2020-06-14 07:07 UTC, schlessera commented
The "full integration" was originally meant to refer to the AMP Optimizer library in the PHP ecosystem, for which we don't have a link yet, but which will soon be a thing.

2020-06-14 17:09 UTC, amedina commented
Got it; that makes sense. For now the wording reads well and corresponds
precisely to the current state. We will calibrate as the library and the
integration evolve. The important point is to convey the fact that the AMP
plugin provides the capability of generating optimized AMP with server-side
rendering out of the box.

On Sun, Jun 14, 2020 at 12:07 AM Alain Schlesser <notifications@github.com>
wrote:

> The "full integration" was originally meant to refer to the AMP Optimizer
> library in the PHP ecosystem, for which we don't have a link yet, but which
> will soon be a thing.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ampproject/amp-wp/pull/4841#issuecomment-643728461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD3R2NIJSDL65YUUEZHBALRWRZMNANCNFSM4N4XBBZA>
> .
>

2020-06-14 17:17 UTC, dnobles003 reviewed
Thank you.