Add PHP 8 as a build job on Travis; bump some jobs up to PHP 7.4
Automattic/amp-wp pull request #4894
Opened 2020-06-20 02:15 UTC by pierlon

## Summary

This PR adds a build job to run unit tests against PHP 8, and disallows the build job for PHP 7.4 unit tests to fail without notification. It also bumps one of the build jobs for the Optimizer unit tests from PHP 7.3 to 7.4.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-06-21 17:10 UTC, pierlon commented
The [errors and failures](https://travis-ci.org/github/ampproject/amp-wp/jobs/700616525#L776) from the PHP 8 job are related to image processing operations in WP and can't be fixed by the plugin (for example, `gdimage` resources are now `GdImage` objects, cf. https://github.com/php/php-src/pull/4714)

2020-06-22 16:26 UTC, westonruter approved these changes
LGTM but I defer to @schlessera

2020-06-22 17:49 UTC, schlessera requested changes
Apart from the PHP version check that can be done faster, LGTM!

2020-06-22 17:49 UTC, schlessera commented on lib/optimizer/src/TransformationEngine.php
> +            if (version_compare('7.1', PHP_VERSION, '<')) {
No need for a complex `version_compare()` here, this can be done faster like this:
```suggestion
            if (PHP_VERSION_ID >= 70100)) {
```

2020-06-22 18:49 UTC, merged