Setup wizard reader themes: indicate which themes can't be installed
Automattic/amp-wp pull request #4945
Opened 2020-06-25 20:07 UTC by johnwatkins0

[WIP: Depends on #4909]

## Summary

Fixes #4801 

When displaying the reader themes screen, this update sorts the themes into those that can be installed and those which can't be installed by the current user on the current system. For example, if the user is not able to install any themes, it will look like this:

<img width="692" alt="Screen Shot 2020-06-25 at 1 27 18 PM" src="https://user-images.githubusercontent.com/9020968/85789938-0d069780-b6f5-11ea-8e17-fb4721775041.png">

Additionally, we filter the current active theme out of the list because it would make no sense for the site's main theme and reader theme to be the same.

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-06-28 05:53 UTC, westonruter commented
Just noticed that the Legacy screenshot is not tall enough: 

![image](https://user-images.githubusercontent.com/134745/85939284-ee58fa00-b8c8-11ea-96ad-55b61cacde62.png)

cc @jwold

2020-06-28 06:02 UTC, westonruter commented on includes/class-amp-reader-themes.php
> +			case 'classic' === $theme['slug'] || wp_get_theme( $theme['slug'] )->exists():
We're going to change this to `legacy` right?

2020-06-28 06:02 UTC, westonruter commented on tests/e2e/specs/amp-onboarding/reader-themes.js
>  		expect( titleText ).toBe( 'AMP Classic' );
We need to change “Classic” to “Legacy”, correct?

2020-06-28 16:20 UTC, jwold commented
1. Yes let’s change classic to legacy 
2. All the screenshots should be the ratio of the legacy (i think)
GitHub <notifications@github.com> wrote:
“@westonruter commented on this pull request.”


“In includes/class-amp-reader-themes.php:”

> @@ -270,7 +270,7 @@ public function get_theme_availability( $theme ) {

 			case get_stylesheet() === $theme['slug']:
 				return self::STATUS_ACTIVE;
 
-			case wp_get_theme( $theme['slug'] )->exists():
+			case 'classic' === $theme['slug'] || wp_get_theme( $theme['slug'] )->exists():
“We're going to change this to legacy right?”


“In tests/e2e/specs/amp-onboarding/reader-themes.js:”

>  		await page.$eval( '[for="theme-card__classic"]', ( el ) => el.click() );
 		let titleText = await page.$eval( '.selectable--selected h2', ( el ) => el.innerText );
 		expect( titleText ).toBe( 'AMP Classic' );
“We need to change “Classic” to “Legacy”, correct?”

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-29 16:52 UTC, pierlon requested changes

2020-06-29 16:52 UTC, pierlon commented on assets/src/setup/style.css
> +input[type="radio"][disabled] {
When the "Next" button is focused, the button text disappears:

![image](https://user-images.githubusercontent.com/16200219/85970071-d52f7680-b9b8-11ea-9ff7-bffe5f7a12d5.png)

Also, the non-primary buttons don't show a focused state. I guess it's because of the border color being the same as the button's background.

2020-06-29 16:52 UTC, pierlon commented on assets/src/setup/pages/choose-reader-theme/index.js
> +		() => themes.filter( ( { availability } ) => 'active' !== availability ),
This throws the following error when navigating back to the "Theme Selection" page when reader mode is not the selected template mode:

```
Uncaught TypeError: can't access property "filter", themes is null
```

2020-06-29 16:53 UTC, johnwatkins0 commented
@westonruter I have pushed updates to (1) change "classic" to "legacy" and (2) set a max height on reader theme screenshots that is equal to the legacy theme screenshot.

2020-06-29 17:00 UTC, johnwatkins0 commented on assets/src/setup/style.css
> +input[type="radio"][disabled] {
Thanks. I've updated the focus states.

2020-06-29 17:09 UTC, pierlon approved these changes

2020-06-29 18:18 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +							{ __( 'Uninstallable themes', 'amp' ) }
Could you please rename `uninstallable` to `unavailable` (or `nonInstallable`) across the codebase (e.g. in the in this file and in `ThemeCard`)? I realized that this is misleading: like it's telling you the list of themes which you can uninstall, but that's not what we intend! 😄

2020-06-29 18:21 UTC, westonruter requested changes

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/style.css
> +.choose-reader-theme__uninstallable label {
```suggestion
.choose-reader-theme__unavailable {
	padding-top: 6rem;
}

.choose-reader-theme__unavailable label {
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +									uninstallable={ true }
```suggestion
							{ unavailableThemes.map( ( theme ) => (
								<ThemeCard
									key={ `theme-card-${ theme.slug }` }
									screenshotUrl={ theme.screenshot_url }
									unavailable={ true }
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/theme-card.js
> + * @param {boolean} props.uninstallable Whether the theme is not automatically installable in the current environment.
```suggestion
 * @param {boolean} props.unavailable Whether the theme is not automatically installable in the current environment.
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/theme-card.js
> +export function ThemeCard( { description, homepage, screenshotUrl, slug, name, uninstallable } ) {
```suggestion
export function ThemeCard( { description, homepage, screenshotUrl, slug, name, unavailable } ) {
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/theme-card.js
> +						disabled={ Boolean( uninstallable ) }
```suggestion
						disabled={ Boolean( unavailable ) }
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/theme-card.js
> +	uninstallable: PropTypes.bool,
```suggestion
	unavailable: PropTypes.bool,
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +	const { availableThemes, uninstallableThemes } = useMemo(
```suggestion
	const { availableThemes, unavailableThemes } = useMemo(
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +					collections.uninstallableThemes.push( theme );
```suggestion
					collections.unavailableThemes.push( theme );
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +			{ availableThemes: [], uninstallableThemes: [] },
```suggestion
			{ availableThemes: [], unavailableThemes: [] },
```

2020-06-29 18:21 UTC, westonruter commented on assets/src/setup/pages/choose-reader-theme/index.js
> +							{ __( 'Uninstallable themes', 'amp' ) }
```suggestion
				{ 0 < unavailableThemes.length && (
					<div className="choose-reader-theme__unavailable">
						<h3>
							{ __( 'Unavailable themes', 'amp' ) }
```

2020-06-29 18:30 UTC, westonruter approved these changes

2020-06-29 19:32 UTC, merged