Prevent sanitization of some Core theme style elements in Customizer preview
Automattic/amp-wp pull request #5019
Opened 2020-07-10 03:32 UTC by pierlon

## Summary

This PR prevents the sanitization of certain style elements that are enqueued by some Core themes in the Customizer preview. These style elements need to be unaltered as some features implemented by these themes (such as color customization) refer to them by their ID, and if the ID cannot be found, then the feature will appear to be broken.

Fixes #5006.

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-07-10 04:08 UTC, westonruter requested changes
I also can see that the Additional CSS is broken in the Customizer. That should be fixed by also adding `$dev_mode_xpaths[] = '//style[ @id = "wp-custom-css" ]';` to `amp_get_content_sanitizers()`

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
Since this is going to be a common issue for every theme that has `custom-background` theme support, let's put this rather here:

https://github.com/ampproject/amp-wp/blob/01202bbfcf46bf466459501679cb550072c4a97e/includes/amp-helper-functions.php#L1476-L1480

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-theme-colors" ]',
See above

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-theme-colors" ]',
Since three core themes use the same ID for the `style` element, let's go ahead and also add this to `amp_get_content_sanitizers` since it is likely other themes will do the same: https://wpdirectory.net/search/01ECVDT8NKJYA2VERA5DSTRYA1

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
See above

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
See above

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
See above

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
See above

2020-07-10 04:08 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +		// We can't use the `amp_dev_mode_element_xpaths` filter here as AMP_Dev_Mode_Sanitizer has already been
Actually, we can use use `amp_dev_mode_element_xpaths` _if_ we switch this method to being `static` rather than non-`static`. 

I know this is not intuitive, but `static` methods get called before template rendering and thus before the sanitizers run. See the `$static` arg for `get_theme_features`:

https://github.com/ampproject/amp-wp/blob/01202bbfcf46bf466459501679cb550072c4a97e/includes/sanitizers/class-amp-core-theme-sanitizer.php#L429-L484

2020-07-10 04:27 UTC, pierlon commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +		// We can't use the `amp_dev_mode_element_xpaths` filter here as AMP_Dev_Mode_Sanitizer has already been
I started out with the method being static, but I realized that the core sanitizer runs after the dev mode sanitizer, so the `amp_dev_mode_element_xpaths` filter would be useless.

2020-07-10 04:33 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +		// We can't use the `amp_dev_mode_element_xpaths` filter here as AMP_Dev_Mode_Sanitizer has already been
The instantiated core sanitizer runs after the dev mode sanitizer, the static methods run before: 

https://github.com/ampproject/amp-wp/blob/01202bbfcf46bf466459501679cb550072c4a97e/includes/class-amp-theme-support.php#L361-L365

2020-07-10 04:34 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +		// We can't use the `amp_dev_mode_element_xpaths` filter here as AMP_Dev_Mode_Sanitizer has already been
Oh right, but `amp_get_content_sanitizers()` is called right before this:

https://github.com/ampproject/amp-wp/blob/01202bbfcf46bf466459501679cb550072c4a97e/includes/class-amp-theme-support.php#L356-L365

2020-07-10 04:35 UTC, westonruter commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +		// We can't use the `amp_dev_mode_element_xpaths` filter here as AMP_Dev_Mode_Sanitizer has already been
OK, disregard my comment then 😊

2020-07-10 04:40 UTC, pierlon commented on includes/sanitizers/class-amp-core-theme-sanitizer.php
> +						'//style[ @id = "custom-background-css" ]',
Added the common list of style element XPaths to `amp_get_content_sanitizers()` in https://github.com/ampproject/amp-wp/pull/5019/commits/a01c983fd85662f5d3108017e6e73c34310f0619.

2020-07-11 22:15 UTC, westonruter approved these changes
@pierlon Everything checked out when I tested all the core themes in Reader mode, except for one thing that stood out which will confuse users: the Cover Template section that Twenty Twenty adds. This section will serve no purpose in the AMP Customizer when Twenty Twenty is the Reader theme if the active theme doesn't also have the same cover page template as Twenty Twenty. So I've amended the PR with logic to deactivate the section when this is the case.

Please double check my changes for anything that looks amiss. I've updated the PR description to reflect the changes.

2020-07-11 22:18 UTC, pierlon commented on src/ReaderThemeLoader.php
> + * This class does not implement Conditional because other services need to be able to always be able to access this
```suggestion
 * This class does not implement Conditional because other services need to always be able to access this
```

2020-07-11 22:52 UTC, pierlon commented
> Nevertheless, if someone is using Twenty Twenty as the Reader Theme and they are using something else as the active theme, then no pages will be assigned to this Twenty Twenty-specific template.

But what if there _was_ a page using the "Cover Template" page template before switching to Reader mode?

2020-07-11 23:04 UTC, westonruter commented
If the cover template is not available in the _active_ theme (a non-Twenty Twenty theme) then if I have Twenty Twenty set as the Reader theme then there shouldn't be any Cover Template options since the user wouldn't have been able to select cover template in the active theme, right? Posts are not edited with the Reader theme active, so Cover Template options should be hidden.

2020-07-11 23:15 UTC, westonruter commented
In other words, it only makes sense to show the Cover Template section on the Customizer if both the active theme and the reader theme have this template.

2020-07-11 23:33 UTC, pierlon commented
Right, but if there was a post created from that template with Twenty Twenty active before switching to Reader mode, and if the Reader mode theme is Twenty Twenty, the user wouldn't be able to edit the "Cover Template" settings in the Customizer when customizing the Reader theme.

2020-07-11 23:35 UTC, westonruter commented
That's right, but that should be exceedingly rare scenario. The usual case will be for someone to have active some theme that lacks this cover template and that they will then use Twenty Twenty as the Reader theme, and they'll be confused by what that Customizer section is for.

2020-07-11 23:35 UTC, westonruter commented
Also, in this scenario, the next time they try editing the page after switching the active theme away from Twenty Twenty, then the page template would be removed from being the Cover Template since the active theme doesn't have that template anymore.

2020-07-11 23:39 UTC, pierlon commented
Yea that's true. I'm OK with the change then :+1:.

2020-07-11 23:43 UTC, westonruter commented
Thank you for thinking it through. 👍

2020-07-11 23:43 UTC, merged