Add/internal docs
Automattic/amp-wp pull request #5218
Opened 2020-08-11 04:02 UTC by westonruter

## Summary

Fixes #5119

This PR adds the necessary `@internal` tags so that phpdoc output can successfully exclude the API surface we do not intend for developers to touch.

When a class has a `@internal` (or `@deprecated`) tag, then it is omitted from the index. If there is a method that does an action or applies a filter, those hooks will be included in the index unless they too have `@internal`. Hooks that have PhpDoc like “This filter is documented in…” are omitted. A couple filters that lacked phpdoc were supplied with it. The `@since` tag was also added in various places.

Functions are included in the index unless they have the `@internal` tag.

The following table is derived from the following script:

```bash
wp eval-file bin/create-phpdoc-index.php
```

My hope is that the logic in the script can be easily ported for the actual generation of the HTML phpdoc.

Type | Name
-----|-----
action | `amp_customizer_enqueue_preview_scripts`
action | `amp_customizer_enqueue_scripts`
action | `amp_customizer_init`
action | `amp_customizer_register_settings`
action | `amp_customizer_register_ui`
action | `amp_extract_image_dimensions_batch_callbacks_registered`
action | `amp_init`
action | `amp_plugin_update`
action | `amp_post_template_include_{$template_type}`
action | `amp_print_analytics`
action | `pre_amp_render_post`
class | `AMP_Base_Embed_Handler`
class | `AMP_Base_Sanitizer`
filter | `amp_analytics_entries`
filter | `amp_comment_posted_message`
filter | `amp_content_embed_handlers`
filter | `amp_content_max_width`
filter | `amp_content_sanitizers`
filter | `amp_css_transient_monitoring_sampling_range`
filter | `amp_css_transient_monitoring_threshold`
filter | `amp_customizer_get_settings`
filter | `amp_customizer_is_enabled`
filter | `amp_customizer_post_type`
filter | `amp_dev_mode_element_xpaths`
filter | `amp_dev_mode_enabled`
filter | `amp_enable_optimizer`
filter | `amp_enable_ssr`
filter | `amp_extract_image_dimensions_batch`
filter | `amp_extract_image_dimensions_get_user_agent`
filter | `amp_frontend_show_canonical`
filter | `amp_get_permalink`
filter | `amp_is_enabled`
filter | `amp_mobile_client_side_redirection`
filter | `amp_mobile_user_agents`
filter | `amp_mobile_version_switcher_link_text`
filter | `amp_mobile_version_switcher_styles_used`
filter | `amp_normalized_dimension_extractor_image_url`
filter | `amp_optimizer_config`
filter | `amp_options_menu_is_enabled`
filter | `amp_parsed_css_transient_caching_allowed`
filter | `amp_post_status_default_enabled`
filter | `amp_post_template_analytics`
filter | `amp_post_template_customizer_settings`
filter | `amp_post_template_data`
filter | `amp_post_template_dir`
filter | `amp_post_template_file`
filter | `amp_post_template_metadata`
filter | `amp_pre_get_permalink`
filter | `amp_pre_is_mobile`
filter | `amp_query_var`
filter | `amp_reader_themes`
filter | `amp_schemaorg_metadata`
filter | `amp_site_icon_url`
filter | `amp_skip_post`
filter | `amp_supportable_post_types`
filter | `amp_supportable_templates`
filter | `amp_to_amp_excluded_urls`
filter | `amp_to_amp_linking_element_excluded`
filter | `amp_to_amp_linking_enabled`
filter | `amp_validation_error`
filter | `amp_validation_error_default_sanitized`
filter | `amp_validation_error_sanitized`
filter | `amp_validation_error_source_file_editor_url_template`
filter | `amp_validation_error_source_file_path`
function | `amp_generate_script_hash()`
function | `amp_get_permalink()`
function | `amp_get_slug()`
function | `amp_is_available()`
function | `amp_is_canonical()`
function | `amp_is_dev_mode()`
function | `amp_is_legacy()`
function | `amp_remove_endpoint()`
function | `is_amp_endpoint()`
function | `post_supports_amp()`

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-08-13 16:51 UTC, westonruter commented
Let's add `amp_` prefixes with aliases for `is_amp_endpoint()` and `post_supports_amp()`.

2020-08-13 18:20 UTC, westonruter commented
All of the non-deprecated API surface now has `amp_` prefixing.

2020-08-13 19:05 UTC, pierlon requested changes

2020-08-13 19:05 UTC, pierlon commented on bin/create-phpdoc-index.php
> + * @param null  $class           Class name the function belongs to.
```suggestion
 * @param array         $parsed_function Parsed function.
 * @param string|null  $class            Class name the function belongs to. Defaults to null.
```

2020-08-13 19:39 UTC, westonruter commented on bin/create-phpdoc-index.php
> + * @param null  $class           Class name the function belongs to.
Aside: This entire file will probably be deleted with the changes that @schlessera is introducing.

2020-08-13 21:21 UTC, pierlon commented
@googlebot I consent.

2020-08-13 21:31 UTC, pierlon commented
Updated some references of `amp_is_endpoint` and `post_supports_amp` in https://github.com/ampproject/amp-wp/pull/5218/commits/dbe56b44a3cc054410d127aeff2050263fbcb6a1 and https://github.com/ampproject/amp-wp/pull/5218/commits/b1e6575193680130b761af65f1f6d8d177fd8f54.

2020-08-13 21:31 UTC, pierlon approved these changes

2020-08-13 22:21 UTC, merged

2020-08-14 05:42 UTC, schlessera commented on includes/amp-helper-functions.php
> + * @deprecated Use amp_is_endpoint() instead.
`Use amp_is_endpoint() instead.` => `Use amp_is_request() instead.`

2020-08-14 05:42 UTC, schlessera commented on includes/amp-helper-functions.php
> + * @deprecated Use amp_is_endpoint() instead.
I'll send in a quick PR for this.

2020-08-14 05:46 UTC, schlessera commented on includes/amp-helper-functions.php
> + * @deprecated Use amp_is_endpoint() instead.
See https://github.com/ampproject/amp-wp/pull/5231