Always normalize to use HTML5 doctype
Automattic/amp-wp pull request #5464
Opened 2020-10-05 17:04 UTC by westonruter

## Summary

There appears to be a bug in `\AmpProject\Dom\Document::normalizeDocumentStructure()` in which it assumes the only non-HTML5 doctype that may appear in the page is HTML 4.0 Transitional. This does not account for other doctypes, including HTML 4.01 Strict, XHTML 1.0 Strict, etc. This ensures the doctype is always set to be HTML5.

Fixes #5462

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-10-05 17:05 UTC, westonruter commented on lib/common/src/Dom/Document.php
> +        $doctype = preg_replace( '#<!doctype\s*html[^>]+?>#si', self::DEFAULT_DOCTYPE, $doctype );
```suggestion
        $doctype = preg_replace( '#<!doctype\s+html[^>]+?>#si', self::DEFAULT_DOCTYPE, $doctype );
```

2020-10-05 17:07 UTC, westonruter commented
This needs some more tests in `lib/common/tests/Dom/DocumentTest.php` to ensure that other standard doctypes are removed.

2020-10-06 15:47 UTC, schlessera requested changes

2020-10-06 15:47 UTC, schlessera commented on lib/common/src/Dom/Document.php
> +        $doctype = preg_replace('#<!doctype\s+html[^>]+?>#si', self::DEFAULT_DOCTYPE, $doctype);
Just for consistency, I'd move the regular expression into a constant as well to have it together with the others.

2020-10-06 16:48 UTC, westonruter commented on lib/common/src/Dom/Document.php
> +        $doctype = preg_replace('#<!doctype\s+html[^>]+?>#si', self::DEFAULT_DOCTYPE, $doctype);
Cool. Done in 2b074aeda.

2020-10-07 06:43 UTC, schlessera approved these changes

2020-10-07 06:52 UTC, merged