Use external amp-toolbox library instead of lib/ subfolder
Automattic/amp-wp pull request #5582
Opened 2020-11-06 17:14 UTC by schlessera

## Summary

This PR removes the `lib/` subfolder and adapts the Composer file and the build instructions to use the external `ampproject/amp-toolbox-php` library instead.

This PR does not add namespace scoping to the library, assuming that any other WordPress plugin/theme should rely on the plugin's presence if they need access to the library => TBD!

Fixes #4567

## Checklist

- [x] My pull request is addressing an open issue (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2020-11-06 17:58 UTC, pierlon commented
@schlessera one more change to be made:

```diff
diff --git a/docs/src/Cli/GenerateCommand.php b/docs/src/Cli/GenerateCommand.php
--- a/docs/src/Cli/GenerateCommand.php	(revision c0c7c7245f3f547d42a9675cb3cebfe22cf1aa29)
+++ b/docs/src/Cli/GenerateCommand.php	(date 1604685464461)
@@ -246,7 +246,6 @@
 	private function get_excluded_dirs() {
 		return [
 			'#^.*/amp/(assets|bin|build|docs|node_modules|tests|vendor)/*#',
-			'#^.*/amp/lib/(common|optimizer)/*#',
 		];
 	}
 
```

2020-11-06 19:10 UTC, pierlon requested changes
A few places where `ampproject/optimizer` is still in use:

https://github.com/ampproject/amp-wp/blob/f972507736c3e16cbb88accc9771d14e926b4334/includes/deprecated.php#L213

https://github.com/ampproject/amp-wp/blob/9addb6739858dd25337a615ea05186dabfc8632a/tests/php/src/Helpers/ErrorComparison.php#L12

https://github.com/ampproject/amp-wp/blob/a6514231d6e15568d7698c86eb5f404b552e3ff2/src/Transformer/AmpSchemaOrgMetadataConfiguration.php#L19

2020-11-06 19:10 UTC, pierlon commented on Gruntfile.js
>  		'vendor/*/*/.git',
The `.github` folder in `ampproject/amp-toolbox` can be excluded. At the same time since it's a common folder let's ignore it for all dependencies.

```suggestion
		'vendor/*/*/.git',
		'vendor/*/*/.github',
```

2020-11-06 19:10 UTC, pierlon commented on Gruntfile.js
> +		'vendor/ampproject/amp-toolbox/bin',
the `.phpcs.xml.dist` file n `ampproject/amp-toolbox` can be excluded.

```suggestion
		'vendor/ampproject/amp-toolbox/bin',
		'vendor/ampproject/amp-toolbox/.phpcs.xml.dist',
```

2020-11-09 23:54 UTC, pierlon commented
Changes look OK. I'm rebasing the PR since there's a merge conflict with the `composer.lock` file.

2020-11-09 23:58 UTC, pierlon commented
Also updating the patch to allow for the PHP 8 job to run since it's outdated.

2020-11-10 00:06 UTC, pierlon approved these changes

2020-11-10 07:16 UTC, westonruter approved these changes
LGTM 😄

2020-11-10 07:16 UTC, westonruter commented on bin/ci/after-wp-install.sh
> +index 5a150f830..f670267f8 100644
Aside: do we even need this context? It will get out of date often.

2020-11-10 07:17 UTC, merged