Prevent empty query var from causing false positive endpoint detection
Automattic/amp-wp pull request #5804
Opened 2021-01-24 05:17 UTC by westonruter

## Summary

Amends #5558. See #2204.

Thanks to @milindmore22 for pointing this out, there's a bug with in how the AMP endpoints are detected. In particular, when a non-AMP URL is request with an empty query var, e.g. `?foo=`, the result is the URL erroneously being identified as an AMP one. The reason for this is that I was removing the endpoint from the URL and then checking of the endpoint-removed URL was not equal to the original URL as a shortcut to identify an AMP URL. This, however, doesn't work because `remove_query_var()` doesn't preserve the distinction between a query var with an empty value and one with no value:

```
wp> remove_query_arg( 'foo', '?bar=' )
=> string(4) "?bar"
wp> remove_query_arg( 'foo', '?bar' )
=> string(4) "?bar"
```

Notice how `?bar=` and `?bar` both end up the same as `?bar` when being passed into `remove_query_arg()`.

So the fix is to check if the URL has the endpoint first, and then if it has it, proceed with removing it. This avoids the false positive.

## Checklist

- [ ] My pull request is addressing an open issue (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-01-25 01:17 UTC, pierlon requested changes

2021-01-25 01:17 UTC, pierlon commented on src/PairedRouting.php
> +			$new_path = $this->get_paired_url_structure()->remove_endpoint( $old_path );
```suggestion
			$new_path = $paired_url_structure->remove_endpoint( $old_path );
```

2021-01-25 03:03 UTC, pierlon approved these changes

2021-01-25 04:26 UTC, merged

2021-04-25 21:40 UTC, westonruter commented
**QA Passed**

Going to `/sample-page/?foo=1` does not serve an AMP page whereas going to `/sample-page/?amp=1` does.