Ensure object-fit and object-position are set on cover block image/video background
Automattic/amp-wp pull request #5927
Opened 2021-02-25 06:08 UTC by westonruter

## Summary

Fixes #5914

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-02-28 01:37 UTC, westonruter commented on includes/embeds/class-amp-core-block-handler.php
> +			'/<(?:img|video)(?= )[^>]* class="[^"]*?wp-block-cover__(?:image|video)-background[^"]*?"[^>]*(?=>)/',
```suggestion
			'/<(?:img|video)(?= )[^>]*? class="[^"]*?wp-block-cover__(?:image|video)-background[^"]*?"[^>]*(?=>)/',
```

2021-03-06 11:55 UTC, pierlon requested changes

2021-03-06 11:55 UTC, pierlon commented on includes/embeds/class-amp-core-block-handler.php
> +			'#<(?:img|video)(?= )[^>]*? class="[^"]*?wp-block-cover__(?:image|video)-background[^"]*?"#',
This regex would match class names like `my-custom-class-wp-block-cover__image-background` or `wp-block-cover__video-background-plugin-baz`, which is unintentional. Here's one way to resolve the issue:

```suggestion
			'#<(?:img|video)(?= )[^>]*? class=(?:"|"[^"]*? )wp-block-cover__(?:image|video)-background(?:"| [^"]*?")#',
```

2021-03-06 11:55 UTC, pierlon commented on includes/embeds/class-amp-core-block-handler.php
> +				// Add the fill layout to skip the needlessly obtaining the dimensions.
```suggestion
				// Add the fill layout to skip needlessly obtaining the dimensions.
```

2021-03-06 11:55 UTC, pierlon commented on includes/embeds/class-amp-core-block-handler.php
> +				// Add object-position from the block attribute's to add to the img/video to be copied onto the amp-img/amp-video.
```suggestion
				// Add object-position from the block's attributes to add to the img/video to be copied onto the amp-img/amp-video.
```

2021-03-06 21:05 UTC, westonruter commented on includes/embeds/class-amp-core-block-handler.php
> +			'#<(?:img|video)(?= )[^>]*? class="[^"]*?wp-block-cover__(?:image|video)-background[^"]*?"#',
This seems to be a bit better:

```suggestion
			'#<(?:img|video)(?= )[^>]*? class="(?:[^"]*? )?wp-block-cover__(?:image|video)-background(?: [^"]*?)?"#',
```

2021-03-06 21:21 UTC, pierlon commented on includes/embeds/class-amp-core-block-handler.php
> +			'#<(?:img|video)(?= )[^>]*? class="[^"]*?wp-block-cover__(?:image|video)-background[^"]*?"#',
That works, and takes less steps to match too!

2021-03-06 22:39 UTC, pierlon approved these changes

2021-03-07 04:36 UTC, westonruter commented
@pierlon There was one last case not yet accounted for: when a cover block doesn't use an `img` element at all (when the background is fixed or repeated). When a cover block was nested inside another cover block, the result was duplication of attributes on the nested cover block. This is addressed in 532c7732663c98b09ca9fe9d1f1fec166a5a4225.

2021-03-07 04:38 UTC, westonruter commented on tests/php/test-class-amp-core-block-handler.php
> +				"\n<div class=\"wp-block-cover has-background-dim\" style=\"background-image:url(https://example.com/wp-content/uploads/2021/02/image.MP_-scaled.jpg);background-position:75.59055118110236% 2.3529
Notice the fix here:

```diff
- object-fit=\"cover\" layout=\"fill\" object-fit=\"cover\" layout=\"fill\"
+ object-fit=\"cover\" layout=\"fill\"
```

2021-03-08 07:19 UTC, merged