Sanitize keys in Server-Timing instead of adding slashes for escaping
Automattic/amp-wp pull request #5941
Opened 2021-03-03 21:09 UTC by westonruter

## Summary

When a sanitizer class is namespaced and verbose server-timing is enabled (via `/?amp_verbose_server_timing=1`), the server-timing rows will include properties that include escaped backslashes, for example: `google\\amp_auto_lightbox_disable\\sanitizer;dur="0.0"`. This ends up breaking the display of Timing data in Chrome DevTools. So this PR sanitizes the key by replacing any non-word characters with underscores.

Given a `Server-Timing` header that contains values like this (with commas replaced by newlines):

```
amp_dom_parse;dur="10.1"
amp_sanitizer;dur="432.5"
amp_dev_mode_sanitizer;dur="0.8"
amp_embed_sanitizer;dur="0.6"
amp_core_theme_sanitizer;dur="0.6"
amp_srcset_sanitizer;dur="0.1"
amp_img_sanitizer;dur="0.3"
amp_form_sanitizer;dur="0.2"
amp_comments_sanitizer;dur="0.2"
amp_video_sanitizer;dur="0.0"
amp_o2_player_sanitizer;dur="0.1"
amp_audio_sanitizer;dur="0.0"
amp_playbuzz_sanitizer;dur="0.2"
amp_iframe_sanitizer;dur="0.0"
amp_gallery_block_sanitizer;dur="0.1"
amp_block_sanitizer;dur="0.0"
amp_script_sanitizer;dur="0.1"
amp_accessibility_sanitizer;dur="0.3"
amp_link_sanitizer;dur="2.8"
google\\amp_auto_lightbox_disable\\sanitizer;dur="0.0"
amp_layout_sanitizer;dur="0.3"
amp_style_sanitizer;dur="408.5"
amp_parse_css;dur="365.1"
amp_shake_css;dur="7.9"
amp_meta_sanitizer;dur="0.2"
amp_tag_and_attribute_sanitizer;dur="16.2"
amp_dom_serialize;dur="8.7"
amp_optimizer;dur="7.7"
```

Before | After
-------|------
<img width="431" alt="Screen Shot 2021-03-03 at 12 46 15" src="https://user-images.githubusercontent.com/134745/109872606-7f832c00-7c21-11eb-9034-c58cf72b2884.png"> | <img width="529" alt="Screen Shot 2021-03-03 at 13 03 33" src="https://user-images.githubusercontent.com/134745/109872612-814cef80-7c21-11eb-977a-edfb0c0d9ba5.png">

Notice how before the timing gets truncated at `google`.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-03-04 18:04 UTC, schlessera requested changes

2021-03-04 18:04 UTC, schlessera commented on src/Instrumentation/Event.php
> +	 * Sanitize key.
A bit of a no-value comment here. How about explaining what we sanitize for?
```suggestion
	 * Sanitize key to use it for an HTTP header label (alphanumeric and dashes/underscores only).
```

2021-03-04 18:33 UTC, schlessera approved these changes

2021-03-04 18:46 UTC, merged

2021-03-09 00:37 UTC, westonruter commented
QA Passed.

Without custom sanitizers:

![image](https://user-images.githubusercontent.com/134745/110400232-230e7b00-802c-11eb-9ff4-f11cd073a9a4.png)

With a custom sanitizer with backslashes due to namespacing:

![image](https://user-images.githubusercontent.com/134745/110400342-53561980-802c-11eb-82ab-666e805be450.png)

The raw response header is:

```
server-timing: amp_dom_parse;dur="6.9",amp_sanitizer;dur="34.2",amp_dev_mode_sanitizer;dur="0.5",amp_embed_sanitizer;dur="0.3",amp_core_theme_sanitizer;dur="0.1",amp_srcset_sanitizer;dur="0.0",amp_img_sanitizer;dur="0.2",amp_form_sanitizer;dur="0.0",amp_comments_sanitizer;dur="0.0",amp_video_sanitizer;dur="0.0",amp_o2_player_sanitizer;dur="0.0",amp_audio_sanitizer;dur="0.0",amp_playbuzz_sanitizer;dur="0.1",amp_iframe_sanitizer;dur="0.1",amp_gallery_block_sanitizer;dur="0.100 15673    0 15673    0     0  64764      0 --:--:nitizer;dur="0.2",amp_link_sanitizer;dur="0.5",google_amp_auto_lightbox_disable_sanitizer;dur="0.0",amp_layout_sanitizer;dur="0.2",amp_style_sanitizer;dur="22.4",amp_parse_css;dur="0.0",amp_shake_css;dur="3.6",amp_meta_sanitizer;dur="0.1",amp_tag_and_attribute_sanitizer;dur="8.6",amp_dom_serialize;dur="4.4",amp_optimizer;dur="3.9"
```

The last entry is `amp_optimizer` which is included in the DevTools table, so this confirms that the custom sanitizer's server timing entry is not causing the output to be truncated.