Avoid failing validation requests when response is redirect
Automattic/amp-wp pull request #6069
Opened 2021-04-14 18:11 UTC by westonruter

## Summary

This fixes a regression introduced by ae367696fb8daa7049cd22c3e1c128081580df31 in #5296 whereby a validation request returned JSON error data if the response was not an AMP page. An exception is needed for when the response is not an AMP page and yet is an HTTP redirect. The `\AMP_Validation_Manager::validate_url()` follows redirects, so we should allow redirects to pass through. 

I discovered this when trying to do `wp amp validation run --limit=1 --include=is_date` which resulted in:

> Warning: Validate URL error (RENDERED_PAGE_NOT_AMP): The requested URL did not result in an AMP page being rendered. URL: https://wordpressdev.lndo.site/?year=2021

This fixes that problem by allowing the request for `https://wordpressdev.lndo.site/?year=2021` to redirect to `https://wordpressdev.lndo.site/2021/`.

Also amends #6063 by undoing erroneous addition of is_callable() check in d0d2137.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-04-14 18:17 UTC, schlessera requested changes

2021-04-14 18:17 UTC, schlessera commented on includes/class-amp-theme-support.php
> +				if ( preg_match( '#^location:#i', $sent_header, $matches ) ) {
```suggestion
				if ( preg_match( '#^location:#i', $sent_header ) ) {
```

2021-04-14 19:56 UTC, schlessera approved these changes

2021-04-14 19:56 UTC, merged

2021-04-26 05:44 UTC, pierlon commented
**QA Passed**

Running the command `wp amp validation run --limit=1 --include=is_date` no longer results in the warning "Validate URL error (RENDERED_PAGE_NOT_AMP)" from occurring, and the URL is validated:

```
Success: 0 crawled URLs have invalid markup kept out of 1 total with AMP validation issue(s); 1 URLs were crawled.
+--------------------------+-----------+---------------+
| Template or content type | URL Count | Validity Rate |
+--------------------------+-----------+---------------+
| date                     | 1         | 100%          |
+--------------------------+-----------+---------------+
```