Sanitize PDF embeds
Automattic/amp-wp pull request #6112
Opened 2021-04-23 23:08 UTC by pierlon

## Summary

Fixes #6083.

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-04-25 07:21 UTC, schlessera requested changes
I pushed an update to the toolbox to add all missing constants for this sanitizer: https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1

Note that those kinds of updates will be almost never needed once https://github.com/ampproject/amp-toolbox-php/pull/100 was merged.

2021-04-25 07:21 UTC, schlessera commented on includes/embeds/class-amp-core-block-handler.php
> +	 * Inject the an inline style attribute to handle PDF embeds not being displayed in some themes (eg. Twenty Twenty).
```suggestion
	 * Inject an inline style attribute to handle PDF embeds not being displayed in some themes (eg. Twenty Twenty).
```

2021-04-25 07:21 UTC, schlessera commented on includes/embeds/class-amp-core-block-handler.php
> +			static function() {
```suggestion
			static function () {
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> + */
Just as a note for now: the file and class docblocks for the sanitizers need some general overhaul. I'm not marking anything here to fix this for this PR, as the above is consistent with the rest. But the current way of documenting these:

- Fails to take all WPCS rules into account.
- Has value-less content that just repeats the code.
- Has the wrong package annotation.

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +	public function sanitize_pdf( DOMElement $element ) {
The code can now make use of the extended `AmpProject\Dom\Element`.
```suggestion
	 * @param Element $element Object element.
	 */
	public function sanitize_pdf( Element $element ) {
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +			$element->parentNode instanceof DOMElement
```suggestion
			$element->parentNode instanceof Element
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +		$elements = $this->dom->getElementsByTagName( 'object' );
Requires `composer update` for https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1
```suggestion
		$elements = $this->dom->getElementsByTagName( Tag::OBJECT );
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +			if ( $element->getAttribute( Attribute::TYPE ) === 'application/pdf' ) {
Requires `composer update` for https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1
```suggestion
			if ( $element->getAttribute( Attribute::TYPE ) === Attribute::TYPE_PDF ) {
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +			Attribute::SRC    => $element->getAttribute( 'data' ),
Requires `composer update` for https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1
```suggestion
			Attribute::SRC    => $element->getAttribute( Attribute::DATA ),
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +		$title = $element->getAttribute( 'aria-label' );
Requires `composer update` for https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1
```suggestion
		$title = $element->getAttribute( Attribute::ARIA_LABEL );
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +		$amp_element = AMP_DOM_Utils::create_node( $element->ownerDocument, 'amp-google-document-embed', $attributes );
Requires `composer update` for https://github.com/ampproject/amp-toolbox-php/pull/169/files?diff=unified&w=1
```suggestion
		$amp_element = AMP_DOM_Utils::create_node( $element->ownerDocument, Extension::GOOGLE_DOCUMENT_EMBED, $attributes );
```

2021-04-25 07:21 UTC, schlessera commented on includes/sanitizers/class-amp-object-sanitizer.php
> +use AmpProject\Layout;
```suggestion
use AmpProject\Attribute;
use AmpProject\Dom\Element;
use AmpProject\Extension;
use AmpProject\Layout;
use AmpProject\Tag;
```

2021-04-25 22:10 UTC, pierlon commented
Thanks for the review @schlessera. I've made use of those new constants in https://github.com/ampproject/amp-wp/pull/6112/commits/55a11f72d7d304b552caafa1aa395b89cb758af4.

2021-04-26 08:55 UTC, schlessera approved these changes

2021-04-26 23:10 UTC, westonruter commented on includes/embeds/class-amp-core-block-handler.php
> +		);
This appears to not not be ideal as the flexbox was used to make the Download button appear on the right, which now doesn

Non-AMP | AMP
-----------|------
![image](https://user-images.githubusercontent.com/134745/116162018-be75b100-a6a9-11eb-884d-0d906f7bac34.png) | ![image](https://user-images.githubusercontent.com/134745/116161962-a3a33c80-a6a9-11eb-9947-81087d4ae911.png)

It seems the more fundamental issue is that the `amp-google-document-embed` doesn't have `width:100%`. I'm gonna try that approach instead.

2021-04-26 23:20 UTC, westonruter commented on includes/embeds/class-amp-core-block-handler.php
> +		);
There, with 7cef7538e2583024fef4805309957de9cf34f8f5:

Non-AMP | AMP
-----------|------
![image](https://user-images.githubusercontent.com/134745/116162018-be75b100-a6a9-11eb-884d-0d906f7bac34.png) | ![image](https://user-images.githubusercontent.com/134745/116162647-15c85100-a6ab-11eb-852f-2a4839c17076.png)
![image](https://user-images.githubusercontent.com/134745/116162706-35f81000-a6ab-11eb-97c4-c038def27764.png) | ![image](https://user-images.githubusercontent.com/134745/116162753-47411c80-a6ab-11eb-957a-cb6a54accc09.png)

2021-04-27 01:33 UTC, westonruter approved these changes

2021-04-27 01:41 UTC, pierlon commented
Thanks for the review @westonruter, changes are :ok_hand:.

2021-04-27 01:53 UTC, merged