Feature/5578 add new settings
Automattic/amp-wp pull request #6501
Opened 2021-07-30 15:37 UTC by delawski

## Summary

Fixes #5578

This PR removes the Mobile redirection toggle from the Onboarding Wizard and adds it to a new "Other" section on the AMP Settings page. The "Other" section also contains a Dev Tools toggle:

<img width="958" alt="Screenshot 2021-07-30 at 18 31 16" src="https://user-images.githubusercontent.com/478735/127677020-ca4314ba-9cb5-45da-9716-17af908520fd.png">

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-07-30 16:25 UTC, delawski commented
I've been trying to fix the failing E2E test but ran out of time. I'm pretty sure there's an easy fix for that.

2021-07-30 16:25 UTC, pierlon commented
> I've been trying to fix the failing E2E test but ran out of time. I'm pretty sure there's an easy fix for that.

No worries. I'll take a look.

2021-07-30 16:26 UTC, delawski commented
> No worries. I'll take a look.

Thanks so much, @pierlon!

2021-07-30 20:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amp-wp?pullRequest=6501) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amp-wp?pullRequest=6501) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: delawski<br/>:x: jwold<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amp-wp?pullRequest=6501) it.</sub>

2021-08-16 18:40 UTC, delawski commented
@jwold Thanks for updating the component!

@pierlon @westonruter I've been able to fix the E2E tests, increase the test coverage, and also resolve the merge conflicts. Now the PR is "green" and I think it's good to go through the final review.

2021-08-19 15:28 UTC, pierlon requested changes

2021-08-19 15:28 UTC, pierlon commented on assets/src/components/dev-tools-toggle/index.js
> +import { User } from '../../components/user-context-provider';
Import can be shortened.

```suggestion
import { User } from '../user-context-provider';
```

2021-08-19 15:28 UTC, pierlon commented on assets/src/components/dev-tools-toggle/index.js
> +			title={ __( 'Enable Dev Tools', 'amp' ) }
I don't think there's a need to use the shortened "Dev" form of "Developer", it may also cause confusion for some.

```suggestion
			title={ __( 'Enable Developer Tools', 'amp' ) }
```

2021-08-19 15:28 UTC, pierlon commented on assets/src/settings-page/developer-tools.js
> +				{ __( 'Only enabled for your user account. This is not a sitewide setting.', 'amp' ) }
We should also mention what it's useful for, similar to how it was on the User Profile page:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/16200219/130085256-3c2dc50f-d51b-413f-90dd-5693f2e227ff.png">

2021-08-19 15:28 UTC, pierlon commented on assets/src/components/unsaved-changes-warning/index.js
> +import { User } from '../../components/user-context-provider';
Import can be shortened.

```suggestion
import { User } from '../user-context-provider';
```

2021-08-19 16:31 UTC, delawski commented on assets/src/settings-page/developer-tools.js
> +				{ __( 'Only enabled for your user account. This is not a sitewide setting.', 'amp' ) }
How about something like this?

![Screenshot 2021-08-19 at 18 30 41](https://user-images.githubusercontent.com/478735/130107275-70a128b4-a42e-429c-9eb4-8a5ed881f6da.png)

2021-08-20 12:56 UTC, delawski commented on assets/src/settings-page/developer-tools.js
> +				{ __( 'Only enabled for your user account. This is not a sitewide setting.', 'amp' ) }
This is addressed in 753175f

2021-09-03 20:36 UTC, pierlon requested changes

2021-09-03 20:36 UTC, pierlon commented on tests/e2e/specs/admin/other-settings.js
> +		// Confirm the mobile redirection is initially disabled.
```suggestion
		// Confirm the mobile redirection is initially enabled.
```

2021-09-03 20:36 UTC, pierlon commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provide only if the plugin has been configured (Onboarding Wizard complete).
```suggestion
 * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
```

2021-09-03 20:37 UTC, pierlon approved these changes
Great work @delawski. Passing onto @westonruter for a final review.

2021-09-10 00:11 UTC, westonruter reviewed
I added long-missing tests for `OptionsMenu` which I've added in 121ca24. 

One of the requirements was:

> Remove "redirect mobile visitors to AMP" toggle from onboarding

I've implemented this in ba02cab.

The main thing left is the E2E tests being fixed, aside from the minor comments I'm leaving here.

2021-09-10 00:11 UTC, westonruter commented on assets/src/settings-page/developer-tools.js
> +				{ __( 'Only enabled for your user account. This is not a sitewide setting. This presumes you have some experience coding with HTML, CSS, JS, and PHP.', 'amp' ) }
```suggestion
				{ __( 'This is a per-user setting. It presumes you have some experience coding with HTML, CSS, JS, and PHP. Once enabled you will have access to Validated URLs and Error Index in the admin menu, the Validate URL item in the admin bar, and the AMP Validation sidebar in the editor.', 'amp' ) }
```

2021-09-10 00:11 UTC, westonruter commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
This prop name and description are unclear to me. Can this be clarified?

2021-09-10 03:42 UTC, westonruter commented
Oh, hold on, E2E tests are passing now! 🤷 

Maybe they'll fail again when the above suggestions are applied.

2021-09-10 12:32 UTC, delawski commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
Yes, the description was totally wrong and the prop name could be better too.

In 418ec3c I've changed those. I'm still not convinced it's clear enough but maybe you can find a better wording?

To make it clearer, I've also replaced the REST _route_ we used: `/wp/v2/users/me` with a general `users` _path_: `/wp/v2/users`. This way, the prop name (`usersResourceRestPath`) should now semantically match its value.

What do you think?

2021-09-10 12:35 UTC, delawski commented
> Oh, hold on, E2E tests are passing now! 🤷

> Maybe they'll fail again when the above suggestions are applied.

That's strange. I don't seem to be getting the E2E error locally. I think this may be some kind of hazard where the Puppeteer doesn't wait for a specific selector before assessing its existence.

2021-09-10 13:46 UTC, westonruter commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
I don't see that `allowConfiguredPluginOnly` was changed.

The users REST path change looks good.

2021-09-10 14:28 UTC, delawski commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
Oh my! I have no idea why I looked at the wrong prop (and "fixed" it). I'll get the `allowConfiguredPluginOnly` clarified.

2021-09-10 14:42 UTC, delawski commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
So this flag is used to allow fetching users data even if the plugin is not fully configured (the Onboarding Wizard has not been completed).

So far, the user data was fetched only after completing the Wizard but right now we need the user data earlier (it's possible to visit the AMP Settings page without going through the Wizard).

Naming is hard. Anything I come up with so far is long and may sound a bit awkward: `skipFetchingIfUnconfiguredPlugin`, `onlyFetchIfPluginIsConfigured`... Suggestions are well appreciated.

2021-09-10 15:41 UTC, westonruter commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
`onlyFetchIfPluginIsConfigured` sounds good to me!

2021-09-13 11:39 UTC, delawski commented on assets/src/components/user-context-provider/index.js
> + * @param {boolean} props.allowConfiguredPluginOnly Provided only for functionality that requires the plugin to be configured.
Perfect! It's been updated in 4b3a89a.

2021-09-13 19:37 UTC, merged