Add overflow buttons to Twitter, Facebook, and Instagram embeds
Automattic/amp-wp pull request #6502
Opened 2021-07-30 22:36 UTC by westonruter

## Summary

As of https://github.com/ampproject/amphtml/pull/35027, Bento versions of `amp-twitter`, `amp-facebook-*`, and `amp-instagram` will require an `overflow` button to resize if they are in the initial viewport. This is to prevent these components from negatively impacting CLS, as they do currently. To prevent the need for users to click the overflow button, we'll eventually need to provide the components the required dimensions up-front as much as possible. See #4729.

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-07-30 23:17 UTC, pierlon requested changes

2021-07-30 23:17 UTC, pierlon commented on includes/embeds/class-amp-twitter-embed-handler.php
> +use AmpProject\Attribute;
These seem to be unused.

```suggestion
```

2021-07-30 23:20 UTC, pierlon approved these changes

2021-07-30 23:52 UTC, merged

2021-11-30 18:39 UTC, delawski commented
**QA Passed**

When embedding a Facebook post, an `overflow` button is added to the markup (it's not visible on the page itself):

![Screenshot 2021-11-30 at 19 36 14](https://user-images.githubusercontent.com/478735/144107638-605cfa9c-5e8d-4506-b64b-f00407904fc5.png)

_Tested on AMP Version 2.2.0-alpha-20211123T020732Z-5405daa_

2021-12-06 12:56 UTC, delawski commented
I did another round of QA using the instructions shared by @westonruter on https://github.com/ampproject/amp-wp/pull/6504#issuecomment-985730141.

Bento versions of `amp-facebook`, `amp-instagram`, and `amp-twitter` (as per #6504) display the "See more" button if placed "above the fold":

| Initial embed | Expanded embed |
| --- | --- |
| ![Screenshot 2021-12-06 at 13 53 12](https://user-images.githubusercontent.com/478735/144849747-f47b0723-d8d0-4c90-bad4-20d66abef268.png) | ![Screenshot 2021-12-06 at 13 53 18](https://user-images.githubusercontent.com/478735/144849769-7962dd26-bce9-4ab3-9a12-aab6f6b744bc.png) |
| ![Screenshot 2021-12-06 at 13 45 47](https://user-images.githubusercontent.com/478735/144849808-0000c897-a74e-4040-b2a5-61a97a0bf4e6.png) | ![Screenshot 2021-12-06 at 13 45 59](https://user-images.githubusercontent.com/478735/144849822-c1d46082-a687-48bc-a61e-61ce856c2cf9.png) |