Add PostFeaturedImage to PrePublishPanel
Automattic/amp-wp pull request #6563
Opened 2021-08-25 10:56 UTC by arthur791004

## Summary

Currently, we can set featured image directly in Post Setting section. If we don't set any featured image and want to publish the post, we will see the notice and encourage to set the featured image. However, we cannot set the featured image immediately at that point. So, adding `PostFeaturedImage` to `PrePublishPanel` to make user able to set it immediately.

### Screenshots

https://user-images.githubusercontent.com/13596067/130777802-3a5338b6-a348-4cca-ad93-a0a3b988eed3.mov

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-08-25 10:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amp-wp?pullRequest=6563) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amp-wp?pullRequest=6563) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amp-wp?pullRequest=6563) it.</sub>

2021-08-26 02:53 UTC, pierlon commented
Hey @arthur791004, thanks for creating this PR. I'm not sure if it was ever intended for one to be able to upload a featured image from the pre-publish panel but given that it is a pre-publish check it would make sense.

cc @westonruter - I'm adding this to the v2.1.4 milestone and classifying it as a bug.

2021-08-26 02:56 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
> +			<PostFeaturedImage
I think it would be a better user experience to let the featured image check stay in the pre-publish panel after they've selected an image, rather than exiting the panel to edit it in the post settings panel.

2021-08-26 03:00 UTC, arthur791004 commented
@pierlon Thanks for your reply! Currently, I'm not very for sure but I think the reason might be that this plugin only adds the notice message to Post Setting section, so only adding the notice to PrePublish panel seems to make sense. The potential problem might be if there is new version for PostFeaturedImage, then this plugin should also update to make it consistent.

2021-08-26 03:03 UTC, arthur791004 commented on assets/src/common/components/pre-publish-panel.js
> +			<PostFeaturedImage
Sounds good! Let me think about how to do it

2021-08-26 03:35 UTC, arthur791004 commented on assets/src/common/components/pre-publish-panel.js
> +			<PostFeaturedImage
I've made the check always staying in the pre-publish panel and also update the recorded video!

2021-08-26 23:42 UTC, pierlon requested changes

2021-08-26 23:42 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
> +	) : null;
I just noticed that since the plugin is filtering the `PostFeaturedImage` component to add the error notice in the Post Settings, we don't need to recreate the notice UI here and instead use the `PostFeaturedImage` component as is. The parameter annotations for this component (`PrePublishPanel`) and `propTypes` object would have to also be adapted of course.

```suggestion
```

2021-08-26 23:42 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
> +			<PostFeaturedImage noticeUI={ noticeUI } />
Suggestion to go along with comment above:

```suggestion
			<PostFeaturedImage />
```

2021-08-26 23:45 UTC, pierlon commented
@arthur791004 Could you also adapt the `\Test_AMP_Post_Meta_Box::test_enqueue_block_assets` test to include `wp-editor` as a script dependency? It would essentially look like this:

```diff
diff --git a/tests/php/test-class-amp-meta-box.php b/tests/php/test-class-amp-meta-box.php
--- a/tests/php/test-class-amp-meta-box.php	(revision 4d9cf3e11d131064ec989986f930c0d3c56d9977)
+++ b/tests/php/test-class-amp-meta-box.php	(date 1630021426599)
@@ -166,6 +166,7 @@
 				'wp-compose',
 				'wp-data',
 				'wp-edit-post',
+				'wp-editor',
 				'wp-element',
 				'wp-hooks',
 				'wp-i18n',
```

2021-08-27 03:25 UTC, arthur791004 commented on assets/src/common/components/pre-publish-panel.js
> +	) : null;
Great 👍 I've removed lots of code that doesn't need now!

2021-08-27 03:57 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
> +PrePublishPanel.propTypes = {};
This can be removed.

```suggestion
```

2021-08-27 03:57 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
>   * @return {Function} Either a plain pre-publish panel, or the panel with a featured image notice.
The `@return` description will have to be updated.

```suggestion
 * @return {Function} A pre-publish panel containing the featured image selection component.
```

2021-08-27 03:57 UTC, pierlon commented on assets/src/common/components/pre-publish-panel.js
> + * Adds a notice to the pre-publish panel for the featured image.
The docblock for this component will also need to be updated to reflect these changes.

```suggestion
 * Adds a pre-publish panel containing the featured image selection component.
 *
 * Note: The `PostFeaturedImage` component would have already been filtered to include
 * any notices for the featured image so there is no need to recreate them here.
```

2021-08-27 05:30 UTC, pierlon commented
I've updated some of the component docblocks to reflect the changes here in https://github.com/ampproject/amp-wp/pull/6563/commits/a3f904ab696760dfd8c6e1ae685b970597b5a662. Also, in https://github.com/ampproject/amp-wp/pull/6563/commits/ac183eacadf9b6461278d37f8bdafb5cc43275e5 I've refactored the way the featured image notice is rendered so that a warning notice is shown when there are validation errors.

2021-08-27 05:39 UTC, pierlon approved these changes
@arthur791004 Thank you for submitting this PR and spending the time to work on it 🙇.

LGTM!

2021-08-27 05:57 UTC, arthur791004 commented
@pierlon Thanks for your quick reply and help to update the comment 👍

2021-08-27 15:14 UTC, westonruter commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
Humm. Why was the message made unconditionally required? If the `required` prop is removed, the resulting message should rather be `Selecting a featured image is recommended for an optimal user experience.`. Although this message as well should be improved (although not necessarily at this time) per https://github.com/ampproject/amp-wp/issues/6075.

2021-08-27 15:15 UTC, westonruter commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
In other words, should these lines not be instead replaced with:

```js
return [ __( 'Selecting a featured image is recommended for an optimal user experience.', 'amp' ) ];
```

2021-08-27 15:19 UTC, westonruter commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
There are many scenarios where no featured image neither available nor desired when someone publishes a post, so we shouldn't mandate Google Search's guidelines as requirements. 

Indeed, the Featured Image is used as the `image` in the Schema.org metadata, and the [Guidelines](https://developers.google.com/search/docs/advanced/structured-data/article#guidelines) make a post eligible to show up _with structured data_ in Search results. The post will still show up in search results without the extra metadata, although it won't be as well presented.

2021-08-27 15:27 UTC, pierlon commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
The idea here is to only let this function validate the image and return a set of validation errors. The text `Selecting a featured image is recommended for an optimal user experience.` is not necessarily an error but a reconmmendation, so I removed it from here.

Instead, the component where this function is being used does a check to see if `media` is nullable, and if so uses the text `Selecting a featured image is recommended for an optimal user experience.`. See https://github.com/arthur791004/amp-wp/blob/1fb801ed0a1fceaffec5087327c391e0f752782d/assets/src/common/components/higher-order/with-featured-image-notice.js#L60-L66.


```js
if ( ! media ) {
	const message = __( 'Selecting a featured image is recommended for an optimal user experience.', 'amp' );
	noticeUI = createNoticeUI( [ message ], 'notice' );
} else {
	const errorMessages = validateFeaturedImage( media, getMinimumFeaturedImageDimensions() );
	noticeUI = errorMessages ? createNoticeUI( errorMessages, 'warning' ) : null;
}
```

2021-08-27 20:28 UTC, westonruter commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
Oh, so this “required” message is actually never shown in the plugin currently but is included in `validateFeaturedImage()` here for completeness?

2021-08-27 20:35 UTC, pierlon commented on assets/src/common/helpers/index.js
> +		return [ __( 'Selecting a featured image is required.', 'amp' ) ];
Yep.

2021-08-30 15:59 UTC, delawski approved these changes
LGTM!

The only thing that looks a bit off to me is the stats: over 4k lines added. Most of that is the `package-lock.json`. I guess it's because of adding the `@wordpress/editor` package to the project.

2021-08-30 16:10 UTC, pierlon commented
Uninstalled then reinstalled the `@wordpress/editor` package and i can confirm it results in the same `package-lock.json`.

2021-08-30 16:12 UTC, merged

2021-08-30 16:14 UTC, westonruter commented
@pierlon This doesn't cherry-pick cleanly into `2.1`. Would you open a PR onto that branch with the conflicts resolved?

2021-08-30 16:15 UTC, pierlon commented
Sure.

2021-08-30 22:53 UTC, westonruter commented
**QA Passed**

Before | After
-------|------
![image](https://user-images.githubusercontent.com/134745/131415628-7c566c02-d361-4212-9b17-baebb024ac21.png) | ![image](https://user-images.githubusercontent.com/134745/131415705-e6ce3438-55b8-4168-b220-d70f60f133d4.png)

And I was able to set the featured image directly from the pre-publish panel:

![image](https://user-images.githubusercontent.com/134745/131415759-bfaebadd-a2ed-4f1a-8a06-b79ab001a9b1.png)