Support request flow.
Automattic/amp-wp pull request #6627
Opened 2021-09-29 06:22 UTC by dhaval-parekh

## Summary

Fixes #5939 

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-09-30 05:51 UTC, pierlon commented on tests/features/support-request.feature
> +Feature: AMP Support Request
It would be great to also test data for a validated URL is in the output as well.

2021-09-30 05:53 UTC, pierlon commented
(Sorry pushed to the wrong branch in https://github.com/ampproject/amp-wp/pull/6627#event-5385117627).

There's a few more [issues in #6147](https://github.com/ampproject/amp-wp/pull/6147#pullrequestreview-753206599) to fix (which is why #5939 was opened), so this PR shouldn't close the issue just yet.

2021-10-07 09:35 UTC, dhaval-parekh commented on tests/features/support-request.feature
> +Feature: AMP Support Request
To test validated URLs we need to mock those. (Like done [previouslly](https://github.com/ampproject/amp-wp/pull/6147/files#diff-96856db892ce2ead70346ad9ca3b309c79be5e73a8f19430bddc5f2e4d805a01R46) ) But it's not the case here.

2021-10-07 09:39 UTC, dhaval-parekh commented
This PR also addresses feedbacks from PR #6147.

2021-10-14 07:29 UTC, pierlon requested changes

2021-10-14 07:29 UTC, pierlon commented on src/Admin/SupportLink.php
> +		return 'admin_init';
This action is not called on the front-end and so the "Get support" link is no longer being added to the admin bar.

Registering the service on `wp_loaded` should do:

```suggestion
		return 'wp_loaded';
```

If going that route I'd also recommend making the admin related filters only run when on an admin screen by wrapping them in a `is_admin()` condition:

```diff
diff --git a/src/Admin/SupportLink.php b/src/Admin/SupportLink.php
--- a/src/Admin/SupportLink.php	(revision 889a6074e39d0d39d25f9e98470c7fd90483db19)
+++ b/src/Admin/SupportLink.php	(date 1634189337883)
@@ -51,14 +51,16 @@
 		// Add support link to Admin Bar.
 		add_action( 'admin_bar_menu', [ $this, 'admin_bar_menu' ], 105 );
 
-		// Add support link to meta box.
-		add_filter( 'amp_validated_url_status_actions', [ $this, 'amp_validated_url_status_actions' ], 10, 2 );
+		if ( is_admin() ) {
+			// Add support link to meta box.
+			add_filter( 'amp_validated_url_status_actions', [ $this, 'amp_validated_url_status_actions' ], 10, 2 );
 
-		// Add support link to Post row actions.
-		add_filter( 'post_row_actions', [ $this, 'post_row_actions' ], PHP_INT_MAX, 2 );
+			// Add support link to Post row actions.
+			add_filter( 'post_row_actions', [ $this, 'post_row_actions' ], PHP_INT_MAX, 2 );
 
-		// Plugin row Support link.
-		add_filter( 'plugin_row_meta', [ $this, 'plugin_row_meta' ], 10, 2 );
+			// Plugin row Support link.
+			add_filter( 'plugin_row_meta', [ $this, 'plugin_row_meta' ], 10, 2 );
+		}
 
 	}
 

```

2021-10-14 07:29 UTC, pierlon commented on src/Admin/SupportScreen.php
> +		$support_data = $this->injector->make( SupportData::class, [ 'args' => $args ] );
After taking a closer look, I think instantiating `SupportData` via the injector makes things overly complicated. Directly creating a `SupportData` object should be simple enough here, and therefore there would be no need for `Injector`.

```suggestion
		$support_data = new SupportData( $args );
```

2021-10-14 07:29 UTC, pierlon commented on src/Admin/SupportScreen.php
> +		$data         = $support_data->get_data();
Alternatively, to get the data in one line:

```suggestion
		$data = ( new SupportData( $args ) )->get_data();
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportCliCommand.php
> +		$support_data = $this->injector->make( SupportData::class, [ 'args' => $args ] );
Same suggestion as above, creating the `SupportData` object should be simple enough.

```suggestion
		$support_data = new SupportData( $args );
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +		$this->urls = array_map( AMP_Validated_URL_Post_Type::class . '::normalize_url_for_storage', $this->urls );
As @westonruter suggested in https://github.com/ampproject/amp-wp/pull/6147#discussion_r707765434, it would be better to use a closure here (and in other places throughout this class), especially for static analysis purposes.


```suggestion
		$this->urls = array_map(
			static function ( $url ) {
				return AMP_Validated_URL_Post_Type::normalize_url_for_storage( $url );
			},
			$this->urls 
		);
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +					$json_last_error,
`$json_last_error` would be an integer here, so it would not give any real meaning if this error were to be logged. I'd recommend using a unique error code to identify where the error came from.

```suggestion
					'malformed_json_amp_insight_endpoint,
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +			$site_health     = new WP_Site_Health();
Would be best to get the `WP_Site_Health` instance if possible.

```suggestion
			if ( method_exists( 'WP_Site_Health', 'get_instance' ) ) {
				$site_health = WP_Site_Health::get_instance();
			} else {
				$site_health = new WP_Site_Health();
			}
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +		$file  = fopen( $error_log_path, 'r' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_fopen
We should suppress any errors that may be thrown upon attempting to read the file.

```suggestion
		$file  = @fopen( $error_log_path, 'r' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_fopen
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +		fclose( $file );
It'd be good to check if the file is a resource that can be read from before attempting to read from it:

```suggestion
		if ( is_resource( $file ) ) {
			while ( ! feof( $file ) ) {
				$line = fgets( $file );
				array_push( $lines, $line );
				$line_count = count( $lines );
				if ( $line_count > $no_of_lines ) {
					array_shift( $lines );
				}
			}

			fclose( $file );
		}
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
> +			array_push( $lines, $line );
```suggestion
			$lines[] = $line;
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportData.php
>  		$error_data = static::remove_domain( $error_data );
Any reason for overloading the `remove_domain()` method and not just iterating over the error data and calling `remove_domain()` on each value?

```suggestion
		foreach ( $error_data as $key => $value ) {
			$error_data[ $key ] = self::remove_domain( $value );
		}
```

2021-10-14 07:29 UTC, pierlon commented on src/Support/SupportRESTController.php
> +		$support_data     = $this->injector->make( SupportData::class, [ 'args' => $request_args ] );
Same suggestion as above, creating the `SupportData` object should be simple enough.

```suggestion
		$support_data = new SupportData( $args );
```

2021-10-14 10:19 UTC, dhaval-parekh commented on src/Support/SupportData.php
>  		$error_data = static::remove_domain( $error_data );
Internally `self::remove_domain()` will do the same thing if the provided value is an array. I kept that part in `self::remove_domain()` because `$error_data` can be multi-dimension array.

2021-10-14 10:31 UTC, dhaval-parekh commented on src/Support/SupportRESTController.php
> +		$support_data     = $this->injector->make( SupportData::class, [ 'args' => $request_args ] );
Originally it was `$support_data = new SupportData( $args );`. I have used an injector after suggestions from the previous PR.

2021-10-14 10:53 UTC, dhaval-parekh commented on src/Support/SupportData.php
> +			array_push( $lines, $line );
Addressed in [39e51e6](https://github.com/ampproject/amp-wp/pull/6627/commits/39e51e68a80dc30f28b041c21f51ab49886ec180)

2021-10-14 10:54 UTC, dhaval-parekh commented on src/Support/SupportData.php
> +		fclose( $file );
Addressed in [39e51e6](https://github.com/ampproject/amp-wp/pull/6627/commits/39e51e68a80dc30f28b041c21f51ab49886ec180)

2021-10-14 10:54 UTC, dhaval-parekh commented on src/Support/SupportData.php
> +		$file  = fopen( $error_log_path, 'r' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_read_fopen
Addressed in [39e51e6](https://github.com/ampproject/amp-wp/pull/6627/commits/39e51e68a80dc30f28b041c21f51ab49886ec180)

2021-10-14 10:54 UTC, dhaval-parekh commented on src/Admin/SupportLink.php
> +		return 'admin_init';
Addressed in [39e51e6](https://github.com/ampproject/amp-wp/pull/6627/commits/39e51e68a80dc30f28b041c21f51ab49886ec180)

2021-10-14 16:27 UTC, pierlon commented on src/Support/SupportRESTController.php
> +		$support_data     = $this->injector->make( SupportData::class, [ 'args' => $request_args ] );
Hmm yea, but unless I'm missing something there's no benefit in creating the `SupportData` via the injector as its not a service or anything. cc @westonruter.

2021-10-14 17:11 UTC, westonruter commented on assets/src/components/amp-support/index.js
> +							__( 'In order to best assist you, please click the Send Data button below to send the following site information to our private database. Once you have done so, copy the the resulting Support
```suggestion
							__( 'In order to best assist you, please tap the Send Data button below to send the following site information to our private database. Once you have done so, copy the the resulting Support UUID in the blue box that appears and include the ID in a new <a href="%s" rel="noreferrer" target="_blank">support forum topic</a>. You do not have to submit data to get support, but our team will be able to help you more effectively if you do so.', 'amp' ),
```

2021-10-14 17:11 UTC, westonruter commented on src/Support/SupportRESTController.php
> +		$support_data     = $this->injector->make( SupportData::class, [ 'args' => $request_args ] );
Another example of using the injector to create a class can be found in `PairedRouting`:

https://github.com/ampproject/amp-wp/blob/002f88e8096a8870c666244577d533311728804f/src/PairedRouting.php#L252-L263

While in practice it makes no difference, in theory the injector is better because this could reference an interface instead of an actual class, and the bindings defined in `AmpWpPlugin` could automatically route the class to instantiate. This could make it easier to test with a mock, as I understand. 

Also, by using `make` the injector is able to re-use instances which are listed among the shared instances in `AmpWpPlugin`, which isn't possible otherwise.

So yeah, I understand from dependency injection that classes should generally not be instantiated directly. 

cc @schlessera

2021-10-14 19:06 UTC, pierlon commented on src/Support/SupportRESTController.php
> +		$support_data     = $this->injector->make( SupportData::class, [ 'args' => $request_args ] );
Thanks for the explanation @westonruter. In this scenario we wouldn't be benefiting from using the injector, since the class being instantiated does not require any sort of dependency resolution and so would not make use of the bindings or shared instances provided by `AmpWpPlugin`. However,  I do understand the benefits of using the injector with regards to testing especially, so after giving it more thought I'm OK with the current implementation.

2021-10-14 19:11 UTC, pierlon approved these changes
This looks good, passing onto @westonruter for a final review.

2021-10-14 19:11 UTC, pierlon commented on src/Support/SupportData.php
>  		$error_data = static::remove_domain( $error_data );
Ah I see. Not a fan of overloading `remove_domain()` and returning multiple data types however as that increases code complexity.

2021-10-18 20:44 UTC, westonruter approved these changes
I've addressed some of my PR feedback with commits.

2021-10-18 20:44 UTC, westonruter commented on src/Admin/SupportLink.php
> +		if ( is_admin() ) {
Not strictly required since outside the admin these actions won't do anything, but it doesn't hurt.

2021-10-18 20:44 UTC, westonruter commented on src/Admin/SupportScreen.php
> +		$support_data = $this->injector->make( SupportData::class, [ 'args' => $args ] );
Another alternative:

```suggestion
		$support_data = $this->injector->make( SupportData::class, compact( 'args' ) );
```

2021-10-18 20:44 UTC, westonruter commented on src/Support/SupportCliCommand.php
> +	 *
Why ignore coverage?

2021-10-18 20:44 UTC, westonruter commented on src/Support/SupportData.php
> +			fclose( $file );
While this looks like it will do the job, it is still reading through the entire file. It is using less memory now, which is good, but it could be more optimal by only seeking through the file starting from the end. For example: https://stackoverflow.com/a/15017711/93579

2021-10-18 20:44 UTC, westonruter commented on src/Support/SupportData.php
> +			$content
At this point `$content` could possibly be a `bool`.

2021-10-18 20:44 UTC, westonruter commented on src/Support/SupportCliCommand.php
> +	 *
Ah, because now it is covered in the feature test.

2021-10-18 20:44 UTC, westonruter commented on tests/php/src/Support/SupportDataTest.php
> +		$this->assertInstanceOf( 'WP_Error', $response );
Minor thing: better to use the `class` constant:

```suggestion
		$this->assertInstanceOf( WP_Error::class, $response );
```

2021-10-18 20:45 UTC, westonruter commented on src/Support/SupportData.php
> +			fclose( $file );
This would still be good to do.

2021-10-18 20:56 UTC, merged