Add option to keep AMP data upon uninstalling of plugin
Automattic/amp-wp pull request #6632
Opened 2021-10-03 08:04 UTC by dhaval-parekh

## Summary

Fixes #6486 

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2021-10-05 21:48 UTC, westonruter requested changes

2021-10-05 21:48 UTC, westonruter commented on includes/amp-helper-functions.php
> +	// @Todo Eliminate this once https://core.trac.wordpress.org/ticket/20578 has finally landed.
```suggestion
	// @todo Eliminate this once https://core.trac.wordpress.org/ticket/20578 has finally landed.
```

2021-10-05 21:48 UTC, westonruter commented on includes/amp-helper-functions.php
> + *
```suggestion
 *
 * @since 2.2
 * @internal
 *
```

2021-10-05 21:48 UTC, westonruter commented on src/Option.php
> +	const KEEP_AMP_DATA = 'keep_amp_data';
Instead of `keep_amp_data` let's use `delete_data_at_uninstall` where it defaults to `true`.

2021-10-05 21:48 UTC, westonruter commented on src/OptionsRESTController.php
> +						'default' => false,
Per above, we can default this to `true`.

2021-10-05 21:48 UTC, westonruter commented on includes/uninstall-functions.php
> +	$keep_amp_data = \AMP_Options_Manager::get_option( Option::KEEP_AMP_DATA );
Humm, did you test this on an actual site? The `AMP_Options_Manager` class is not loaded at uninstallation so this causes a fatal error:

![image](https://user-images.githubusercontent.com/134745/136101176-28547ad4-2951-4360-9447-365b94ac1444.png)

(Perhaps the plugin's autoloader _should_ get initialized during uninstallation.)

2021-10-05 21:48 UTC, westonruter commented on tests/php/test-amp-helper-functions.php
> +	 * @covers amp_modify_plugin_description
```suggestion
	 * @covers ::amp_modify_plugin_description()
```

2021-10-05 21:48 UTC, westonruter commented on includes/options/class-amp-options-manager.php
> +		Option::KEEP_AMP_DATA           => false,
Per above, this can be `true` by default instead with the rename.

2021-10-05 21:48 UTC, westonruter commented on assets/src/settings-page/data-removal.js
> + * Developer tools section of the settings page.
```suggestion
 * Data deletion at uninstallation toggle on the settings page.
```

2021-10-05 21:48 UTC, westonruter commented on assets/src/settings-page/data-removal.js
> +	const keepAmpData = editedOptions?.keep_amp_data;
This might as well be moved after the `fetchinOptions` condition.

2021-10-05 21:48 UTC, westonruter commented on assets/src/settings-page/data-removal.js
> +		<section className="developer-tools">
```suggestion
		<section className="delete-data-at-uninstall">
```

2021-10-05 21:48 UTC, westonruter commented on assets/src/settings-page/data-removal.js
> +				title={ __( 'Keep my data', 'amp' ) }
```suggestion
				title={ __( 'Delete plugin data at uninstall', 'amp' ) }
```

2021-10-05 21:48 UTC, westonruter commented on assets/src/settings-page/data-removal.js
> +				{ __( 'When you delete the plugin you have the choice to have the data remain or removed.', 'amp' ) }
```suggestion
				{ __( 'When you uninstall the plugin you have the choice of whether its data should also be deleted. Examples of plugin data include the settings, validated URLs, and transients used to store image dimensions and parsed stylesheets.', 'amp' ) }
```

2021-10-05 21:48 UTC, westonruter commented on amp.php
> + * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Deletion Note:</strong> To delete all plugin data with uninstallation, fi
```suggestion
 * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Uninstall Note:</strong> To control whether all data from this plugin is deleted at uninstallation, first activate the plugin, go to the Other section on the Settings screen, and set the “Delete plugin data at uninstall” toggle.</em>
```

2021-10-05 22:18 UTC, westonruter approved these changes

2021-10-06 10:08 UTC, delawski approved these changes
Frontend-wise the code looks good to me.

2021-10-06 21:27 UTC, pierlon approved these changes

2021-10-06 21:27 UTC, pierlon commented on amp.php
> + * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Uninstall Note:</strong> To control whether all data from this plugin is
Wondering if the install note should be on a separate line for better visibility 🤔

```suggestion
 * Description: An easier path to great Page Experience for everyone. Powered by AMP. <br><em class="amp-deletion-notice"><strong>Uninstall Note:</strong> To control whether all data from this plugin is deleted at uninstallation, first activate the plugin, go to the Other section on the Settings screen, and set the “Delete plugin data at uninstall” toggle.</em>
```

Before | After
---|---
<img width="833" alt="image" src="https://user-images.githubusercontent.com/16200219/136283611-d65f27c8-9f0e-4fe8-aec8-facad3efa59a.png"> | <img width="795" alt="image" src="https://user-images.githubusercontent.com/16200219/136283574-a2e3d7d9-c5e8-4653-b1be-b433c300e1e6.png">

2021-10-06 21:27 UTC, pierlon commented on src/Option.php
> +	 * The key of the option storing whether the to delete AMP data upon uninstalling of plugin.
```suggestion
	 * The key of the option storing whether to delete AMP data upon uninstalling the plugin.
```

2021-10-06 21:36 UTC, westonruter commented on amp.php
> + * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Uninstall Note:</strong> To control whether all data from this plugin is
Ideally, yes. Unfortunately, the `br` tag is not allowed. Only `abbr`, `acronym`, `code`, `em`, `strong`, and `a` are allowed: https://github.com/WordPress/wordpress-develop/blob/ed9f437fc098ba2c9ba18eda0fa341ecd0476ca9/src/wp-admin/includes/plugin.php#L173-L186

2021-10-06 21:58 UTC, pierlon commented on amp.php
> + * Description: An easier path to great Page Experience for everyone. Powered by AMP. <em class="amp-deletion-notice"><strong>Uninstall Note:</strong> To control whether all data from this plugin is
Oh I see, unfortunate indeed.

2021-10-06 22:20 UTC, merged