Enable AMP admin menu in admin bar for WordPress version prior to 5.6
Automattic/amp-wp pull request #6797
Opened 2021-12-17 12:05 UTC by dhaval-parekh

## Summary

Fixes #

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2022-01-19 11:57 UTC, delawski requested changes
I tested out this PR locally on WP 4.9. The menu item still doesn't show up for me.

I guess it may be due to a fact that the Dev Tools is not turned on for me:

![Screenshot 2022-01-19 at 12 48 16](https://user-images.githubusercontent.com/478735/150124060-13bce662-d230-46f6-b6a0-0a42ea7492dd.png)

It's not possible to turn it option on - there's no toggle on the AMP Settings screen (see: ff7e7b7 and a related the discussion: https://github.com/ampproject/amp-wp/pull/6773#discussion_r768101011). A direct POST request doesn't change the option value, too:

```js
wp.apiFetch( { path: '/wp/v2/users/me', method: 'POST', data: {
	amp_dev_tools_enabled: true,
} } );
```

Maybe there's something I'm missing?

2022-01-25 18:41 UTC, westonruter commented
I think we could decide against needing to make this change to fix the issue, based on https://github.com/ampproject/amp-wp/issues/6793#issuecomment-1021493449. The only user report for this is just for E2E testing and not an actual normal end user, and a better solution for E2E would be an alternative way to detect for validation errors.

2022-03-07 13:08 UTC, delawski commented
> I think we could decide against needing to make this change to fix the issue, based on [#6793 (comment)](https://github.com/ampproject/amp-wp/issues/6793#issuecomment-1021493449). The only user report for this is just for E2E testing and not an actual normal end user, and a better solution for E2E would be an alternative way to detect for validation errors.

Should we close this PR then?

2022-03-07 17:19 UTC, westonruter commented
Yeah, I think so. #maybelater

2022-03-07 17:19 UTC, closed without merging