Update AMP menu item based on AMP settings when it saved.
Automattic/amp-wp pull request #6878
Opened 2022-02-02 12:03 UTC by NikhilJoshua

## Summary

Fixes #6714 

These changes will add or remove "Validated URL" and "Error Index" menu items from the main AMP menu when the user changes the "Enable Developer Tool" option and save it instead of adding or removing it after page load.

https://user-images.githubusercontent.com/8474784/150963351-aa807e45-69bc-4307-aafb-766f57333cc2.mp4

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2022-02-25 12:36 UTC, dhaval-parekh approved these changes
Changes looks good to me.

2022-03-03 05:33 UTC, westonruter requested changes

2022-03-03 05:33 UTC, westonruter commented on assets/src/settings-page/index.js
> +		};
This would make sense to be defined at the top level of the module, rather than as a nested callback.

2022-03-03 05:33 UTC, westonruter commented on assets/src/settings-page/index.js
> +			addAmpDevOptions( __( 'Validated URLs', 'amp' ), 'edit.php?post_type=amp_validated_url' );
The URL here is actually already exported as part of `amp-settings` as `VALIDATED_URLS_LINK`.

2022-03-03 05:33 UTC, westonruter commented on assets/src/settings-page/index.js
> +			addAmpDevOptions( __( 'Error Index', 'amp' ), 'edit-tags.php?taxonomy=amp_validation_error&post_type=amp_validated_url' );
To go along with the previous, we could add `ERROR_INDEX_LINK` as exported from PHP.

2022-03-03 05:33 UTC, westonruter commented on assets/src/settings-page/index.js
> +				document.querySelectorAll( '#toplevel_page_amp-options ul li a[href*="post_type=amp_validated_url"]' )
While this works, it seems it could be hardened a bit to prevent removing unexpected menu items.

2022-03-03 05:33 UTC, westonruter commented
I apologize for my delay in reviewing. Please take a look at my suggested changes in 41dac1dc49ad1f49359ee8333fb9ce6dae10329a.

2022-03-03 06:05 UTC, NikhilJoshua commented
> I apologize for my delay in reviewing. Please take a look at my suggested changes in [41dac1d](https://github.com/ampproject/amp-wp/commit/41dac1dc49ad1f49359ee8333fb9ce6dae10329a).

Thanks for the updates :) @westonruter

2022-03-03 16:20 UTC, westonruter approved these changes

2022-03-03 16:23 UTC, merged