Fix react unique key prop error in `<SiteScanNotice />` component
Automattic/amp-wp pull request #7448
Opened 2023-02-03 13:10 UTC by thelovekesh

## Summary

Fix the react unique key prop error while rendering `<SiteScanNotice />` in the plugin's admin screen which is usually triggered when someone activates a plugin.

Error:
![image](https://user-images.githubusercontent.com/54371619/216611387-2c59ea38-8c14-471e-bcd0-a52dd2260d09.png)

Originally discovered in https://github.com/ampproject/amp-wp/pull/7421#issuecomment-1405672781 while working on #7421.

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2023-02-03 17:12 UTC, westonruter commented on assets/src/admin/site-scan-notice/notice.js
> +					key={themesWithAmpIncompatibility.length}
Are these the right keys? The lengths could be the same.

2023-02-03 17:13 UTC, westonruter requested changes

2023-02-03 17:13 UTC, westonruter commented on assets/src/admin/site-scan-notice/notice.js
> +					key={pluginsWithAmpIncompatibility.length}
```suggestion
					key="plugins"
```

2023-02-03 17:13 UTC, westonruter commented on assets/src/admin/site-scan-notice/notice.js
> +					key={themesWithAmpIncompatibility.length}
Would this be better?

```suggestion
					key="themes"
```

2023-02-03 17:13 UTC, westonruter commented on assets/src/admin/site-scan-notice/notice.js
> +					key={pluginsWithAmpIncompatibility.length}
Or should it rather be:

```suggestion
					key={`plugins${pluginsWithAmpIncompatibility.length}`}
```

2023-02-03 17:24 UTC, westonruter approved these changes
Thanks for proactively addressing this!

2023-02-03 17:32 UTC, merged

2023-02-06 09:02 UTC, pavanpatil1 commented
QA passed ✅ 


Cross-checked the issue, Fix is working as expected. Now the console error after plugin compatibility scanning is not visible. 

**Before**
![image](https://user-images.githubusercontent.com/44057535/216926231-a98ef37a-51cf-474e-9182-58726f85dc85.png)


**After fix**

https://user-images.githubusercontent.com/44057535/216929113-55555d1c-6395-4f6f-9e36-2cb6da51c0e1.mp4