Fix `withMediaLibraryNotice` issue with latest Gutenberg releases
Automattic/amp-wp pull request #7711
Opened 2024-01-08 08:35 UTC by thelovekesh

## Summary
Update `` to extend logic from [`MediaUpload.buildAndSetFeatureImageFrame`](https://github.com/WordPress/gutenberg/blob/trunk/packages/media-utils/src/components/media-upload/index.js#L301).

Fixes #7710 

## Checklist

- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

2024-01-08 13:35 UTC, milindmore22 commented
Tested for the following Media blocks
1) Image
2) Gallery
3) Cover Image
4) Media Tet
5) Audio
6) Video

The issue seems resolved.

2024-01-08 19:38 UTC, westonruter requested changes
Just a couple tweak suggestions. However, I'd love to learn more about how you came up with the code here. I see some of it is forked from underlying code either in Gutenberg or core. Could you add more links to the original code being overridden? Or otherwise if you came up with the code on your own, I'd love to learn how you learned :)

2024-01-08 19:38 UTC, westonruter commented on assets/src/block-editor/components/with-media-library-notice.js
> +			 *
This overrides a method, right? So it should link to https://github.com/WordPress/wordpress-develop/blob/71cb3f861573f065c6d7d7ef1975bf98532239b4/src/js/media/views/frame/select.js#L167-L179

2024-01-08 19:38 UTC, westonruter commented on assets/src/block-editor/components/with-media-library-notice.js
> +		 * @see {@link https://github.com/WordPress/gutenberg/blob/debddee2ace15263c08c66b5f5a43a9e17bf5d0c/packages/media-utils/src/components/media-upload/index.js#L301} Original MediaUpload buildAndSetF
For some reason I'm getting a syntax problem here in PhpStorm:

![image](https://github.com/ampproject/amp-wp/assets/134745/6137c102-95c7-469e-9f64-81e99c70773e)

This fixes it:

```suggestion
		 * Modified from {@link https://github.com/WordPress/gutenberg/blob/debddee2ace15263c08c66b5f5a43a9e17bf5d0c/packages/media-utils/src/components/media-upload/index.js#L301-L316|Original MediaUpload buildAndSetFeatureImageFrame method}.
```

2024-01-08 19:38 UTC, westonruter commented on assets/src/block-editor/components/with-media-library-notice.js
> +			const featuredImageFrame = getFeaturedImageMediaFrame();
```suggestion
			const FeaturedImageFrame = getFeaturedImageMediaFrame();
```

2024-01-08 19:38 UTC, westonruter commented on assets/src/block-editor/components/with-media-library-notice.js
> +			this.frame = new featuredImageFrame({
```suggestion
			this.frame = new FeaturedImageFrame({
```

2024-01-08 19:38 UTC, westonruter commented on assets/src/block-editor/components/with-media-library-notice.js
> +				editing: this.props.value ? true : false,
```suggestion
				editing: Boolean(this.props.value),
```

2024-01-09 04:46 UTC, thelovekesh commented
> However, I'd love to learn more about how you came up with the code here. I see some of it is forked from underlying code either in Gutenberg or core. Could you add more links to the original code being overridden? Or otherwise if you came up with the code on your own, I'd love to learn how you learned :)

I have forked the whole logic from the Gutenberg MediaUpload component and overrode the `buildAndSetFeatureImageFrame()` which only executes when a user clicks to set the featured image in the block editor.

The only piece modified in forked code is `getFeaturedImageMediaFrame()`:
- Override `createSelectToolbar` to hook our notice in the media upload modal.
- Add `suggestedHeight` and `suggestedWidth` in the `wp.media.controller.FeaturedImage` constructor defaults. So later we can get them from the component state.

2024-01-09 05:02 UTC, westonruter approved these changes
Looks great!

2024-01-09 05:03 UTC, merged